### ISSUE TITLE
REST API docs include unsupported options

### ISSUE THREAD

**Issue by snej** [couchbaselabs/couchbase-mobile-portal#102]
The REST API docs seem to be copied from the CouchDB docs. They describe options that come from CouchDB but aren't supported by either CBL or the Gateway. For example, the docs for [_changes](http://developer.couchbase.com/mobile/develop/references/couchbase-lite/rest-api/database/get-changes/index.html) list a bunch of query parameters like `view`, `last-event-id`, `att_encoding_info`, `conflicts`, `descending` that aren't supported.

Unfortunately the only way to find out what options are supported or not is to look at the source code— CBLRouter+Handlers.m for CBL, and the `rest/*_api.go` files in the Gateway.

**Comment by jamiltz** [comment]
Cross checked Sync Gateway GET /_changes https://github.com/couchbaselabs/couchbase-mobile-portal/commit/2ae8af1cdfa03511b295f5876fa04c0eb90b616c

Good to know that all the handlers are in CBLRouter + Handlers.m! I can't find the changes feed query options in this file though. I'd like to cross check CBL GET /_changes with the docs. Can you point me to it?

**Comment by snej** [comment]
Ah, the changes feed code is in CBLRouter+Changes.m :)
