### ISSUE TITLE
Article regarding how sync works

### ISSUE THREAD

**Issue by jessliu** [couchbaselabs/couchbase-mobile-portal#103]
Ironically, we do not have a good article that details how the sync actually works. We have how to administer, what channels are, etc. but we don't have an article to address basic questions like:
- What happens when a push/pull request is made?
- How is conflict handled?
- How is disrupted sync handled?

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2970](https://issues.couchbase.com/browse/DOC-2970) and will get it fixed as soon as possible.
