### ISSUE TITLE
Improve docs on connecting to password-protected buckets

### ISSUE THREAD

**Issue by snej** [couchbaselabs/couchbase-mobile-portal#108]
People are having trouble connecting SG to a password-protected Couchbase Server bucket. See [this thread](https://groups.google.com/d/msgid/mobile-couchbase/a0d50c3a-46ce-4e65-8a0b-88388e06bdee%40googlegroups.com?utm_medium=email&utm_source=footer), in particular the message where Jeremy describes the solution (5 August 8:58pm).

It sounds like part of the problem is confusion about what the credentials are for a Couchbase Server bucket; that's not something I know anything about. Maybe we can link to some Couchbase Server docs?

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2967](https://issues.couchbase.com/browse/DOC-2967) and will get it fixed as soon as possible.
