### ISSUE TITLE
Example code missing under native-api, view

### ISSUE THREAD

**Issue by lichenyang2** [couchbaselabs/couchbase-mobile-portal#113]
Under http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/view/index.html
1. Section "Understanding map functions", the example code for Objective C is missing - No code example is currently available.
2. The example code for all C# are missing.   It should be added or have the tab removed.
3. Not sure whether we need the "Android" tab for each code example.   Android is not a language like C#, Objective C.   The content for "Android" and "Java" are all identical.

**Comment by jamiltz** [comment]
Based on the input above we should check for the presence of an android tab in the markdown documentation and:

1. If there's one then we render a java and android tab.
2. If there isn't one then we render the java tab twice marking it as android the second time.
