### ISSUE TITLE
Sync gateway _changes, restricted heartbeat range not documented

### ISSUE THREAD

**Issue by ajres** [couchbaselabs/couchbase-mobile-portal#115]
When using long polling with SG _changes feed a heartbeat interval can be set in milli seconds, SG restricts the range of this internally, this should be documented to avoid unexpected behaviour.

// Minimum value of _changes?heartbeat property
const kMinHeartbeatMS = 25 \* 1000

// Default value of _changes?timeout property
const kDefaultTimeoutMS = 5 \* 60 \* 1000

// Maximum value of _changes?timeout property
const kMaxTimeoutMS = 15 \* 60 \* 1000

**Comment by jamiltz** [comment]
@adamcfraser Can you confirm if still applicable?

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2968](https://issues.couchbase.com/browse/DOC-2968) and will get it fixed as soon as possible.
