### ISSUE TITLE
CBL REST API: _replicate doc missing most of the JSON options

### ISSUE THREAD

**Issue by snej** [couchbaselabs/couchbase-mobile-portal#137]
The REST API doc for [_replicate](http://developer.couchbase.com/mobile/develop/references/couchbase-lite/rest-api/server/post-replicate/index.html) only covers three of the many properties available in the JSON body.

Most importantly, it doesn't document how to cancel a replication.

CouchDB documentation is [here](http://docs.couchdb.org/en/latest/api/server/common.html#replicate), but we don't support all those options and we add some of our own.

**Comment by jamiltz** [comment]
I cross checked https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/API/CBLManager.m#L1010-L1059 and the docs http://developer.couchbase.com/mobile/swagger/couchbase-lite/#!/server/post_replicate. I think the two options we're missing in the documentation at this point are:

- attachments: what does it do? I couldn't find it in the CouchDB docs.
- auth: https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/API/CBLManager.m#L916-L943. What is the advantage of auth over passing the cookie in the headers dictionary? I've seen questions about handling cookie expiration and restarting a replication then. Does providing the authorizer automatically handle the cookie expiration?

**Comment by snej** [comment]
`attachments` is an experimental property that can be set to `false` to disable downloading attachments in a pull replication. It's only supported in iOS/Mac.

Specifying auth is higher level than just submitting a cookie. For one thing, it means the app doesn't have to know the details of constructing cookies for different auth systems, or need to deal with re-authenticating when a session expires.

The Swagger spec doesn't seem to have any detail on the request body; it just says "The request message body is a JSON document that contains the following objects."

Other properties are defined in `CBL_ReplicatorSettings.h`:
```c
#define kCBLReplicatorOption_Reset @"reset"
#define kCBLReplicatorOption_Timeout @"connection_timeout"  // CouchDB specifies this name
#define kCBLReplicatorOption_Heartbeat @"heartbeat"         // NSNumber, in ms
#define kCBLReplicatorOption_PollInterval @"poll"           // NSNumber, in ms
#define kCBLReplicatorOption_Network @"network"             // "WiFi" or "Cell"
#define kCBLReplicatorOption_UseWebSocket @"websocket"      // Boolean; default is YES
#define kCBLReplicatorOption_PinnedCert @"pinnedCert"       // NSData or (hex) NSString
#define kCBLReplicatorOption_RemoteUUID @"remoteUUID"       // NSString
#define kCBLReplicatorOption_PurgePushed @"purgePushed"     // Boolean; default is NO
#define kCBLReplicatorOption_AllNew @"allNew"               // Boolean; default is NO
```

These ones are inherited from CouchDB:

* `reset` forces the checkpoint to be reset, i.e. start over from the beginning.
* `connection_timeout` specifies the timeout to use on HTTP requests (milliseconds).
* `heartbeat` specifies the `heartbeat` value to be used in the `_changes` feed request.

These are supported by all 3 of our implementations, I believe:

* `poll` makes a continuous pull replication poll the `_changes` feed, at the given interval in ms, instead of keeping a connection open.
* `network` can be used to restrict the replicator to using only WiFi/Ethernet or only cellular networking.

These are only on iOS/Mac, I believe:

* `websocket` can be set to `false` to disable the use of WebSockets for the `_changes` feed (only on iOS/Mac so far.)
* `pinnedCert` forces an SSL connection to accept _only_ a specific certificate (instead of any valid certificate for that hostname.) This increases security for regular server-based replication, and if you're using P2P it's the only way to make a trustworthy connection. The parameter body can be either the raw certificate data or a SHA-1 digest of it, in base64.
* `remoteUUID` tells the replicator to use the given string as the identifier of the remote server, instead of the URL, when constructing the unique identifier of this replication. This is necessary if the server doesn't have a stable URL, i.e. with P2P.
* `purgePushed` tells a push replicator to purge every document after it successfully pushes it to the server.
* `allNew` tells a push replicator that all the revisions being pushed are new ones that don't yet exist on the server. This improves performance by skipping the `revs_diff` request.

Note: On Mac/iOS, all of these properties can also be set from the native API by adding them to the `CBLReplication.customProperties` dictionary. That isn't available yet on the other platforms, although we ought to add it, as it adds a lot of flexibility.

**Comment by jamiltz** [comment]
Thanks!! The request body schema is specified on the left and users can click model to get the descriptions

![swagger](https://cloud.githubusercontent.com/assets/2589337/17817138/d2744168-6634-11e6-808c-d738f93dc2b3.png)


But it's not straightforward. Need to explore how to make this easier. Added the iOS/Mac and experimental props specifying that they are iOS/Mac only or experimental. Missing auth but I'll add it soon after I try it out and explain the advantage over using cookie headers (its very useful for REST API users that won't need to manage the cookie expiration).

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2966](https://issues.couchbase.com/browse/DOC-2966) and will get it fixed as soon as possible.
