### ISSUE TITLE
Emphasize "Sync Project with Gradle Files" for Android Hello World Sample

### ISSUE THREAD

**Issue by hideki** [couchbaselabs/couchbase-mobile-portal#166]
At Y-Gen Hackathon, a participant tried to Hello World Sample for Android. He only focused on copy-pasting code. He skipped "gradle sync", and he has missing class issue because library was not downloaded. We need extra emphasize for "Sync Project with Gradle Files" section.

http://developer.couchbase.com/mobile/develop/training/build-first-android-app/get-started-studio/index.html

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2963](https://issues.couchbase.com/browse/DOC-2963) and will get it fixed as soon as possible.
