### ISSUE TITLE
Update CBL Rest API for stale parameter on design doc view query

### ISSUE THREAD

**Issue by pasin** [couchbaselabs/couchbase-mobile-portal#173]
This is probably targeted for 1.1.0. 

See http://wiki.apache.org/couchdb/HTTP_view_API for the stale parameter description.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2961](https://issues.couchbase.com/browse/DOC-2961) and will get it fixed as soon as possible.
