### ISSUE TITLE
Conflict Resolution Sample Code should include mergeRevisions() sample

### ISSUE THREAD

**Issue by pasin** [couchbaselabs/couchbase-mobile-portal#176]
Per https://github.com/couchbase/couchbase-lite-ios/issues/617, it's not clear what meta-data should be included into the merged properties when setting to a new revision's .properties property. This may be solved by either :
1. Provide a proper mergeRevisions() sample
2. Instead of use .properties, use .userProperties instead.

Reference Doc Section: http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/document/index.html#Understanding%20Conflicts

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2960](https://issues.couchbase.com/browse/DOC-2960) and will get it fixed as soon as possible.
