### ISSUE TITLE
Add Database.close() method to the API

### ISSUE THREAD

**Issue by pasin** [couchbaselabs/couchbase-mobile-portal#177]
The API needs to be updated according to https://github.com/couchbase/couchbase-lite-ios/commit/9c38f8b4610b04d6f7a65468fe406068e0d33b30.

**Comment by jamiltz** [comment]
Fixed in https://github.com/couchbaselabs/couchbase-lite-api/commit/68426dbca7c3935063f7b93c71b67a058966006d
