### ISSUE TITLE
Ability to preview generated docs of PRs

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-mobile-portal#203]
**Problem**

Docs pull requests are cumbersome to review, since there is nothing that generates a preview.  While it's possible to render a preview locally, it's a bit time consuming and so most people end up just trying to review the XML, which is difficult to read.

What would be ideal would be to have a jenkins job which would see pull requests and kick off a build to render the docs and put them on S3, and then post a link to the github ticket with the pre-rendered docs.  

This is similar in spirit to the way perfrunner is setup with Gerrit.  Whenever a Gerrit change for perfrunner is created, it kicks off a jenkins build that compiles the code and runs the tests, and then it posts the status to the Gerrit ticket.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2962](https://issues.couchbase.com/browse/DOC-2962) and will get it fixed as soon as possible.
