### ISSUE TITLE
Add guide for implementing the CQRS pattern

### ISSUE THREAD

**Issue by zgramana** [couchbaselabs/couchbase-mobile-portal#204]
Steve Yen provided the content for this guide in his Connect 2015 talk ["IRFC – A Design Pattern for Next Generation Business Applications"](http://www.couchbase.com/nosql-resources/presentations/irfc-–-a-design-pattern-for-next-generation-business-applications.html).

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2959](https://issues.couchbase.com/browse/DOC-2959) and will get it fixed as soon as possible.
