### ISSUE TITLE
Link for configuration behind "this example" is incorrect in the creating and querying a view guide

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/couchbase-mobile-portal#230]
On the page at http://developer.couchbase.com/mobile/develop/guides/sync-gateway/accessing-cb-views/creating-and-using-a-view/index.html

Note that the text behind "this example" (which is also a bad way to name a link) seems to be for a sync function, but the prose seems to indicate I'd be using a sync gateway JSON config input file.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2958](https://issues.couchbase.com/browse/DOC-2958) and will get it fixed as soon as possible.
