### ISSUE TITLE
CURL Command Samples for REST APIs

### ISSUE THREAD

**Issue by pasin** [couchbaselabs/couchbase-mobile-portal#232]
I think we should have curl command samples for the REST APIs along with the current HTTP request and response samples.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2957](https://issues.couchbase.com/browse/DOC-2957) and will get it fixed as soon as possible.
