### ISSUE TITLE
[portal feedback] Include reference to getContentURL on Attachment API Ref page

### ISSUE THREAD

**Issue by JeffThomasWriter** [couchbaselabs/couchbase-mobile-portal#235]
8/25/2015 3:30:44   It doesn't have what I need I am writing an app which use photo attachments, and i lost a lot of time becouse i did not find here getContentURL() method which is really usefull when you work with images. nusrat558@gmail.com http://developer.couchbase.com/mobile/develop/references/couchbase-lite/couchbase-lite/attachment/attachment/index.html

I was not able to find the page to refer to.

My assessment:

This looks like adding a simple cross reference to getContentURL, but I do not know where that is; our website search doesn't, really. More broadly, API reference content is absurdly sparse (it should be expanded), and two-way linking between the guide and reference should be improved. I will enter a separate ticket for parts 2 and 3.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2956](https://issues.couchbase.com/browse/DOC-2956) and will get it fixed as soon as possible.
