### ISSUE TITLE
Background-thread section of concurrency guidelines needs more details

### ISSUE THREAD

**Issue by snej** [couchbaselabs/couchbase-mobile-portal#238]
The docs have some Mac/iOS-specific info about [running Couchbase Lite on a background thread](http://developer.couchbase.com/documentation/mobile/1.1.0/develop/guides/couchbase-lite/native-api/manager/index.html#backgroundThreads), which I wrote a few years ago. But in helping a developer with [an issue](https://github.com/couchbase/couchbase-lite-ios/issues/898) I realized there's not enough info.

Two things need to be added:
- If running Couchbase Lite on a background thread, you need to run a runloop on that thread, or notifications won't be delivered.
- It's also possible to run Couchbase Lite on a GCD dispatch_queue.

I can write the docs for this.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2954](https://issues.couchbase.com/browse/DOC-2954) and will get it fixed as soon as possible.
