### ISSUE TITLE
Create SG Distributed Index Guide

### ISSUE THREAD

**Issue by zgramana** [couchbaselabs/couchbase-mobile-portal#240]
Needs to cover:

- [ ] Feature overview
- [ ] Planning and sizing
- [ ] Installation
- [ ] Deployment
- [ ] Configuration
- [ ] Monitoring
- [ ] Resizing
- [ ] Upgrading

**Comment by jamiltz** [comment]
Closing as I believe this is already being tracked in https://github.com/couchbaselabs/couchbase-mobile-portal/issues/299. To re-open if needed.
