### ISSUE TITLE
Query.limit documentation misleading or incorrect

### ISSUE THREAD

**Issue by borrrden** [couchbaselabs/couchbase-mobile-portal#245]
http://developer.couchbase.com/documentation/mobile/current/develop/guides/couchbase-lite/native-api/query/index.html
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/query/query/index.html

The former says "if non-zero" which implies that zero is ignored.  The latter says "the default is '0' meaning unlimited" which is not correct.  A value of zero here will return zero rows.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2953](https://issues.couchbase.com/browse/DOC-2953) and will get it fixed as soon as possible.
