### ISSUE TITLE
Document running cb-backup with Sync Gateway

### ISSUE THREAD

**Issue by JeffThomasWriter** [couchbaselabs/couchbase-mobile-portal#253]
Ticket to track documentation of Sync Gateway ticket 1090. This looks like CBS/SG overlap documentation. Would it go in the CBS docs?

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2951](https://issues.couchbase.com/browse/DOC-2951) and will get it fixed as soon as possible.
