### ISSUE TITLE
Needs to add HelloWorld PhoneGap documentation

### ISSUE THREAD

**Issue by hideki** [couchbaselabs/couchbase-mobile-portal#273]
Currently we have ToDoLite sample for PhoneGap. However, ToDoLite sample is little complicated such as containing facebook stuff. I'd like to suggest to write HelloWorld like documentation for PhoneGap.

To start to write CouchbaseLite PhoneGap plugin app with PhoneGap v5.x for Android platform, in addition to add couchbase lite plugin, needs to do followings:
- Add platforms/android/build-extras.gradle files
- update config.xml to update minimum SDK version to higher than 16 for Android.
- Add cordova-plugin-whitelist plugin 

Above stuff should be clearly documented.

Thanks!

**Comment by jamiltz** [comment]
Done http://developer.couchbase.com/documentation/mobile/1.3/installation/phonegap/index.html
