### ISSUE TITLE
Broken link to list of CBL logging keywords

### ISSUE THREAD

**Issue by snej** [couchbaselabs/couchbase-mobile-portal#274]
From https://github.com/couchbase/couchbase-lite-ios/issues/985 :
>The CBLManager enableLogging documentation refers to a none existing page http://docs.couchbase.com/couchbase-lite/cbl-ios/#useful-logging-channels for a list of types. 
Please provide the correct url to the list of logging types.

**Comment by jamiltz** [comment]
FWIW the link is now http://developer.couchbase.com/documentation/mobile/current/develop/guides/couchbase-lite/native-api/manager/index.html#global-logging-settings
