### ISSUE TITLE
Add Admin REST documentation for :4985/{db}/

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/couchbase-mobile-portal#286]
Currently, it just shows _resync at the below link.

http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/sync-gateway/admin-rest-api/database/index.html

**Comment by jamiltz** [comment]
Covered in swagger spec http://developer.couchbase.com/mobile/swagger/sync-gateway-admin/#!/database/post_db_resync
