### ISSUE TITLE
DP SG Accelerator Docs

### ISSUE THREAD

**Issue by zgramana** [couchbaselabs/couchbase-mobile-portal#299]

**Comment by jamiltz** [comment]
https://github.com/couchbase/sync_gateway/issues/1966

**Comment by adamcfraser** [comment]
Integration with existing site
 - Need to decide whether to include sg_accel information on the default Sync Gateway installation/getting started pages 

Feature overview
 - What sg_accel is, and what it does
   - Include an introductory high level architecture diagram, showing what the cluster topology looks like with and without sg_accel
   - Emphasize that sg_accel is all about scalability, particularly for write throughput
   - Talk about the fact that Sync Gateway nodes still handle all client traffic, and that sg_accel is more of a background processing node
   - Can review the difference between the in-memory channel cache (traditional Sync Gateway) and bucket-backed, distributed channel index (sg_accel)

Performance specs
  - Display performance charts (as defined by PM)
  - Provide some context for what's shown in the charts

Planning and sizing
 - More technical details on planning and sizing.  Two main concerns:
    a. Cluster size
 - Talk about number of sg_accel nodes, number of sg nodes based on expected read/write load (some of this will be based on the information in the performance specs)
 - Maybe talk about size of each node (CPU and memory recommendations, or at least describe the node size used for the perf testing)
    b. sg_accel config
- In particular the num_shards parameter needs to be discussed.  (see notes on https://github.com/couchbaselabs/sync-gateway-accel/issues/39)

 Installation/Deployment/Configuration
- Couchbase Server requirements - sg_accel requires Couchbase Server 4.1.x or higher. 
- Describe the bucket requirements (usual data bucket, new index bucket requirement)
- Cover installation of sg_accel from the download page (should be nearly identical to sync_gateway, aside from config)
- Document the new config options for:
  - sg_accel config
  - sync_gateway config when using sg_accel
- Do we explicitly talk about how to upgrade an existing SG deployment to SG/SGA

 Monitoring
- Information on sg_accel logging
- Do we include information on sg_accel expvars?
- Troubleshooting tips?

Resizing
-  Ability to add and remove sg_accel nodes on the fly up to the num_shards limit
-  How to change the num_shards limit 

Caveats/Notes
 - sg_accel doesn't provide any additional scalability for bucket shadowing.  As today, bucket shadowing is limited to a single Sync Gateway node.  Include details on the upcoming deprecation of bucket shadowing, to be replaced by support for coexistence of SDK and Sync Gateway writes (in an upcoming 2.x release)

**Comment by jamiltz** [comment]
Config:
  - Have standalone SG accel spec
  - Have SG configs related to accel on https://developer.couchbase.com/documentation/mobile/1.3/guides/sync-gateway/config-properties/index.html

Samples: https://github.com/couchbase/sync_gateway/blob/master/examples/basic_sg_accel_config.json

**Comment by jamiltz** [comment]
There's an initial draft on the dev branch.

Questions that came to mind while writing the docs are:

- We had specified `channel_index.server` and `channel_index.bucket` in the SGA config [in the wiki](https://github.com/couchbase/sync_gateway/wiki/Introduction-to-Sync-Gateway-Accelerator#setting-up-your-sync-gateway-accelerator-cluster). But I can't see those properties listed in [config.go](https://github.com/couchbase/sync_gateway/blob/master/rest/config.go#L182-L187). Does it mean they are not needed anymore?
- After downloading sg accel from [here](https://www.couchbase.com/nosql-databases/downloads), I tried to start it with
  
```json
{
  "log": ["HTTP+"],
  "cluster_config":{
    "server":"http://localhost:8091",
    "bucket":"data_bucket",
    "data_dir":"."
  },
  "databases": {
    "app_name": {
      "server": "http://localhost:8091",
      "bucket": "data_bucket",
      "channel_index": {
        "writer": true,
        "server":"http://localhost:8091",
        "bucket":"channel_bucket"
      }
    }
  }
}
```

  but got the following error.

  ```bash
  ~/Downloads/couchbase-sg-accel/bin/sync-gateway sg-accel.json
  
  See [logs](https://gist.github.com/jamiltz/002970088e68d00ffcfb5c7dafe35d49)
  ```

  Any idea why that might be happening?
- Are all of the properties in an SG config also applicable to SGA?

**Comment by jamiltz** [comment]
Closing. Will track in individual ticket.

https://github.com/couchbaselabs/couchbase-mobile-portal/issues/549
https://github.com/couchbaselabs/couchbase-mobile-portal/issues/550
https://github.com/couchbaselabs/couchbase-mobile-portal/issues/551
https://github.com/couchbaselabs/couchbase-mobile-portal/issues/552
https://github.com/couchbaselabs/couchbase-mobile-portal/issues/553
