### ISSUE TITLE
Update SG 1.2.x docs to reflect unsupported user views functionality

### ISSUE THREAD

**Issue by malarky** [couchbaselabs/couchbase-mobile-portal#300]
Accessing views via the SG user port is available but not supported in 1.2 - please update the docs to reflect this.  See [#1493](https://github.com/couchbase/sync_gateway/issues/1493) and [#1499](https://github.com/couchbase/sync_gateway/pull/1499).

**Comment by jamiltz** [comment]
The guide now covers the necessary props in the config file to use views http://developer.couchbase.com/documentation/mobile/1.3/develop/guides/sync-gateway/views/index.html
