### ISSUE TITLE
Update SG 1.1.x docs to reflect unavailable user port view access.

### ISSUE THREAD

**Issue by malarky** [couchbaselabs/couchbase-mobile-portal#301]
Accessing views via the SG user port in 1.1.x does not actually work - please update the docs to reflect this.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2939](https://issues.couchbase.com/browse/DOC-2939) and will get it fixed as soon as possible.
