### ISSUE TITLE
Document sync_gateway_service_install.sh in the Sync Gateway guide

### ISSUE THREAD

**Issue by malarky** [couchbaselabs/couchbase-mobile-portal#302]
There doesn't seem to be any mention at all of `sync_gateway_service_install.sh` in the SG guide.

It would be useful in the "Running Sync Gateway" and/or "Deployment considerations" sections.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2905](https://issues.couchbase.com/browse/DOC-2905) and will get it fixed as soon as possible.
