### ISSUE TITLE
Many missing params in CBL REST view query docs

### ISSUE THREAD

**Issue by snej** [couchbaselabs/couchbase-mobile-portal#306]
The Couchbase Lite [REST view query API docs](http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/rest-api/design-document/get---db--design--design-doc--view--view-name-/index.html) are missing several important query params: `group`, `group_level`, `attachments`, `keys`, `reduce`.

For comparison, here are the [CouchDB docs](http://docs.couchdb.org/en/latest/api/ddoc/views.html#db-design-design-doc-view-view-name). (Although Couchbase Lite doesn't implement _all_ of those. Need to check CBLRouter_Handlers.m.)

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2913](https://issues.couchbase.com/browse/DOC-2913) and will get it fixed as soon as possible.
