### ISSUE TITLE
Doc example wrong for _bulk_get

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/couchbase-mobile-portal#322]
(ported from https://github.com/couchbase/sync_gateway/issues/1727)

Expected: The example response shows a multipart response. 
Actual: The example response does not show a multipart response. 

http://developer.couchbase.com/documentation/mobile/1.2/develop/references/sync-gateway/rest-api/database-public/post-bulk-get/index.html

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to https://issues.couchbase.com/browse/DOC-2930 and will get it fixed as soon as possible.
