### ISSUE TITLE
Update/review the attachment section of integrating w/ external stores guide

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/couchbase-mobile-portal#323]
The existing documentation doesn't cover how to add/remove attachments in the context of a document write.  Should try to do this for 1.3, to also include some of the enhancements being made around attachment handling.

Best approach might be as a guide, as a counterpoint to the one that already exists for CBL.

**Comment by jamiltz** [comment]
[This section](http://developer.couchbase.com/documentation/mobile/1.3/develop/guides/sync-gateway/integrating-external-stores/index.html#importing-attachments) of the integrating with external stores guides covers how to import attachments as base64 inlined in the document body. I believe there is another method to do it using the `/{db}/{id}/{attach}` endpoint. Treating this ticket as the task to revisit the content already online with what's missing and maybe branch it off on a different page.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to https://issues.couchbase.com/browse/DOC-2899 and will get it fixed as soon as possible.
