### ISSUE TITLE
sg-replicate docs should suggest same sync function on both ends

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-mobile-portal#364]
In discussion about https://github.com/couchbase/sync_gateway/issues/1846, @adamcfraser and I realized that having different sync functions on two databases that are being sync'd could lead to unexpected behavior.

The docs should warn against this and suggest using the same sync functions.

**Comment by jamiltz** [comment]
Regarding having the same sync function on both sides, how are the calls to `requireUser`, `requireRole`, `requireAccess` handled since the user's data may not be in the context?
