### ISSUE TITLE
Add note to config.json config docs about updating config users

### ISSUE THREAD

**Issue by ajres** [couchbaselabs/couchbase-mobile-portal#387]
If a user already exists in the backing bucket, the user config in config.json will not be applied.

This is to prevent updates to users via the ADMIN REST api being blown away.

But it can be a little confusing for devs, who might change the "admin_channels" for a user and not see the users doc visibility change after a restart.

To pick up user changes in the config.json, the user record must be removed from the backing bucket before restarting SG.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2904](https://issues.couchbase.com/browse/DOC-2904) and will get it fixed as soon as possible.
