### ISSUE TITLE
TTL docs should cover TTL replication

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/couchbase-mobile-portal#395]
TTL docs should make it clear that TTL values set in Couchbase Lite aren't (currently) replicated to Sync Gateway, and vice-versa.

**Comment by jamiltz** [comment]
This is mentioned in the note on http://developer.couchbase.com/documentation/mobile/1.2/developer-preview/ttl/index.html. Those docs are CBL. The same note could be mentioned in the swagger description of the SG spec.

**Comment by adamcfraser** [comment]
Great - I hadn't seen it on the client side.  I can add it to the SG spec.

**Comment by adamcfraser** [comment]
Fixed with https://github.com/couchbaselabs/couchbase-mobile-portal/commit/e77e329758fe93a8c01f33fae0cd53467a92ebe0
