### ISSUE TITLE
Minor corrections in SG Replication docs (staging version)

### ISSUE THREAD

**Issue by HodGreeley** [couchbaselabs/couchbase-mobile-portal#404]
In [http://developer-stage.cbauthx.com/documentation/mobile/1.2/develop/guides/sync-gateway/running-replications/index.html](http://developer-stage.cbauthx.com/documentation/mobile/1.2/develop/guides/sync-gateway/running-replications/index.html)

- Both one-shot and continuous replications can be run, each run... (break into two sentences at comma)

- two database (plural, so missing s)

- Typo - sencods

- Under Cancelling Replications header, italics starting with endpoint /replicate and "replicationid"(_ issue) 

- endpoint /activetasks italics (_ issue)

**Comment by jamiltz** [comment]
Thanks! Can you check in those updates in https://github.com/couchbaselabs/couchbase-mobile-portal/blob/377-docs-1.3/md-docs/ready/g uides/sync-gateway/running-replications.md ?

**Comment by jamiltz** [comment]
Correction, the link is https://github.com/couchbaselabs/couchbase-mobile-portal/blob/377-docs-1.3/md-docs/ready/guides/sync-gateway/running-replications.md

**Comment by jamiltz** [comment]
Fixed in https://github.com/couchbaselabs/couchbase-mobile-portal/commit/d21213933871f25df4c576d747e5e66ef618aff7
