### ISSUE TITLE
SG Replicate written in terms of replicating databases.  Seems inconsistent/confusing.

### ISSUE THREAD

**Issue by HodGreeley** [couchbaselabs/couchbase-mobile-portal#405]
In [http://developer-stage.cbauthx.com/documentation/mobile/1.2/develop/guides/sync-gateway/running-replications/index.html](http://developer-stage.cbauthx.com/documentation/mobile/1.2/develop/guides/sync-gateway/running-replications/index.html) the text talks about replicating two databases.
It seems potentially confusing.  Are these Couchbase Server databases, CB Lite, ...?  But it's talking about replicating between SG instances.  Since SG doesn't provide persistence itself, it's perhaps the last thing I think of to call a database in the stack.

**Comment by jamiltz** [comment]
Fixed in https://github.com/couchbaselabs/couchbase-mobile-portal/commit/cc46d94e2eca168c5c6c1364f2b19c2516fad643
