### ISSUE TITLE
SG Docker docs

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/couchbase-mobile-portal#428]
Notes from @tleyden:

> Section 1 - walrus:
- Standalone sync gateway w/ Walrus
- Local config via mount  `docker run -v /tmp/mysgconfig.json:/opt/sync-gateway/etc/sync_gateway.json`
- Example how to change the config and run `docker stop && docker rm containerid && docker run`
- Remote config on the web
Section 2 - couchbase server:
- Startup a couchbase container in docker network mycouchbase and volume `-v /opt/couchbase:/opt/couchbase`
- Go to localhost:8091 and set up
- Startup sync gw container in network mycouchbase that points to http://couchbase:8091
Not production recommended: couchbase server should have it’s own host
Section 3 - couchbase server + app:
- Follow Section 2 couchbase server steps
- But docker compose with:
 - Sg container
 - App container
Section 4:
- Multiple SG and/or Couchbase Server containers

Connects to https://github.com/couchbase/sync_gateway/issues/1969

**Comment by jamiltz** [comment]
@tleyden Do you think we should include Docker docs on this page http://developer.couchbase.com/documentation/mobile/1.3/installation/sync-gateway/index.html?

**Comment by tleyden** [comment]
Yeah, but can we just point to them to avoid duplicating the docs?

**Comment by jamiltz** [comment]
Yep that sounds good. https://hub.docker.com/r/couchbase/sync-gateway/ is this the official docker hub documentation?

**Comment by tleyden** [comment]
Nope, we don't have an official image yet.  It's been stalled waiting for the docker folks to review.

**Comment by jamiltz** [comment]
Ok cool we can point to this one then until the official image is out.

**Comment by tleyden** [comment]
Yeah

**Comment by jamiltz** [comment]
@tleyden there's now a link to the docker readme on this page http://developer-stage.cbauthx.com/documentation/mobile/1.3/installation/index.html.
