### ISSUE TITLE
Proper way to set Swagger spec host?

### ISSUE THREAD

**Issue by Prudwell** [couchbaselabs/couchbase-mobile-portal#454]
I'm looking into using swagger for the web portion of my app using the examples [here](https://github.com/couchbaselabs/couchbase-mobile-portal/blob/master/md-docs/ready/guides/sync-gateway/rest-api-client.md) as a starting place. The examples use the specs hosted on developer.couchbase.com which have localhost as the 'host'. 

For my implementation should I be copying the spec.json file to my server and setting my own host in it? If that's the case, how do I know when I need to update my swagger spec file to the latest version when there's an update to the one hosted on developer.couchbase.com? 

Thanks!

EDIT: Ah I now see that swagger-client also has a [setHost()](https://github.com/swagger-api/swagger-js/blob/master/lib/client.js#L577) method, that might be what I'm looking for.

**Comment by jamiltz** [comment]
> For my implementation should I be copying the spec.json file to my server and setting my own host in it?

Yes for the Couchbase Lite spec as it needs to work offline. The spec is JSON so you can load it in memory.

The REST API client guide is [now on the site](http://developer.couchbase.com/documentation/mobile/1.3/develop/guides/sync-gateway/rest-api-client/index.html). The hybrid section uses the setHost method in the PhoneGap plugin http://developer.couchbase.com/documentation/mobile/1.3/develop/guides/sync-gateway/rest-api-client/index.html#hybrid-development. You can use the same with RN.

> how do I know when I need to update my swagger spec file to the latest version when there's an update to the one hosted on developer.couchbase.com?

I don't have an easy answer for this. We don't have versioning on it yet as it was introduced with CBL 1.3. But we'll have it soon. It's updated frequently so maybe by doing an MD5 hash of it and comparing with what you have locally. This is still a process that needs to be figured out. In development, I'd recommend to use the remote URL so you always have the latest and can get updates automatically.

**Comment by Prudwell** [comment]
Sounds great, thanks for the insight!
