### ISSUE TITLE
Authorization Header Authentication for SG?

### ISSUE THREAD

**Issue by Prudwell** [couchbaselabs/couchbase-mobile-portal#459]
So I'm continuing my adventures with using the swagger specs and swagger-client. I'm having difficulty setting up authentication. Right now I have a server side script that accepts username and password then gets a session via the public API and passes back the cookie to the client if authentication succeeds. I'm reading the documentation here

http://developer.couchbase.com/documentation/mobile/1.3/develop/guides/authentication/custom-authentication/index.html

Down near the end:
> Subsequent client requests to the gateway will now include the session in a cookie, which the gateway will recognize. For the cookie to be recognized, your site must be configured so that your app's API and the gateway appear on the same public host name and port.

So I absolutely need to get sync gateway and and my app API on the same domain and even port too? I'm not actually sure how to get them both working on the same port. Are there any other ways to do request authentication besides cookies, such as Authorization headers? Or are there some more detailed examples of sync gateway authentication for web somewhere in the documentation?

Thanks!

**Comment by jamiltz** [comment]
> "your site must be configured so that your app's API and the gateway appear on the same public host name and port"

Yes I think this could be a bit more detailed for readers trying to implement authentication in an app, not a website. Are you looking to use authentication using Couchbase Lite's replicator or in a browser that handles cookie storage automatically? (I guess both use cases could use more description but which one are you looking to implement)

**Comment by Prudwell** [comment]
Ah sorry I should have been more clear. So my product will have both web and hybrid mobile app interfaces. I've got the mobile side of things working with couchbase lite and the react-native-couchbase-lite package and am now trying to get the web side of things talking to sync gateway. 

I'm using react, redux, swagger-client and the swagger specs hosted on developer.couchbase.com. I am trying to use the Set-cookie returned from a successful call to the public sync gateway endpoint [POST /{db}/_session](http://developer.couchbase.com/documentation/mobile/current/develop/references/sync-gateway/rest-api/index.html#operation---db--_session-post) to set a cookie in the user's browser which will then authenticate swagger requests to the sync gateway public API endpoint (this is how it's supposed to work I think?).

Currently I have a simple node/express endpoint which accepts a username/password from my website and then passes them to the POST /{db}/_session sync gateway endpoint. If the request is successful, the node script takes the Set-Cookie from the Sync gateway response and forwards it to the browser. I'm thinking that maybe this won't work because in my current setup, sync gateway and my node/express API are not on the same host due so some issues with docker and localhost on my OSX machine. The set-cookie is coming from a domain that is not the same as the sync gateway.

Maybe I should have my website request a session directly from the sync gateway endpoint so that the cookie is coming from the domain on which the cookie will be used? I'd like to have the authentication go through some server code if possible so I can do more with it in the future. Do I need to figure out a way to have my sync gateway and my custom server API endpoint on the same domain? Are cookies the best way to authenticate ongoing requests with swagger-client in a website to the sync gateway endpoints?

Any insight or thoughts would be much appreciated. Thanks!

**Comment by jamiltz** [comment]
As a temporary workaround you should be able to include the name/password in the url to SG `http://name:pass@localhost:4984/todo`. I think Swagger client has an option to set the name/password.

Now for the cookie things get a bit more tricky when the SG and Web server domains are different as you noted.

> I'm thinking that maybe this won't work because in my current setup, sync gateway and my node/express API are not on the same host due so some issues with docker and localhost on my OSX machine. The set-cookie is coming from a domain that is not the same as the sync gateway.

You can use the `withCredentials` option on XMLHttpRequest to tell the browser to include the cookie in CORS requests. I tried with [this config and JS](https://gist.github.com/jamiltz/82df2bd9f9d022bec3e8899f9f8f59f3) and the request works (without `withCredentials` it returns a 401).

I haven't figured out a way to set the `withCredentials` to true with Swagger though. I'm still looking.

**Comment by Prudwell** [comment]
Cool will give that a shot.

As an aside, I did just try calling the sync gateway session endpoint directly from my site (without the server script middleman) and the Set-Cookie response worked fine. In swagger client I can use that cookie if I set enableCookies: true in the constructor.

```
var publicClient = new Swagger({
    url: 'http://localhost.com:3000/publicSpec.json',
    usePromise: true,
    enableCookies: true
    })
```
This doesn't work for the CORS situation but I can fall back to this way of doing things if I have to. 

I've tried some other methods such as manually adding ClientAuthorizations as shown in the [swagger-client](https://github.com/swagger-api/swagger-js) documentation but no luck so far.

**Comment by jamiltz** [comment]
> but I can fall back to this way of doing things if I have to.

Does it mean that the web server will act as a reverse proxy for sync gateway in that case? (i.e. serving the website and SG on the same domain)

Can you point me to the swagger documentation where you found the `enableCookies` options.

**Comment by Prudwell** [comment]
When I say 'fall back' I mean cutting the web server completely out of the authentication cycle for now. The website would send the username/password to the Sync Gateway session endpoint directly. 

I guess I need to look into that reverse proxy sooner rather than later because I'd really like the authentication to go through server code.

I actually never found documentation for the enableCookies option in swagger-client. I found it via searching for 'cookie' in the source code... The documentation there seems to be a bit incomplete. Here is the location in the source code

[https://github.com/swagger-api/swagger-js/blob/master/lib/client.js#L158](https://github.com/swagger-api/swagger-js/blob/master/lib/client.js#L158)

**Comment by Prudwell** [comment]
Looking further into the source code, it does look like withCredentials is set when using enableCookies.

[https://github.com/swagger-api/swagger-js/blob/master/lib/http.js#L218
](https://github.com/swagger-api/swagger-js/blob/master/lib/http.js#L218
)
And swagger-client uses superagent so here's the documentation on their withCredentials
[https://visionmedia.github.io/superagent/#cors](https://visionmedia.github.io/superagent/#cors)

**Comment by jamiltz** [comment]
> When I say 'fall back' I mean cutting the web server completely out of the authentication cycle for now.

It might be easier to start off without the reverse proxy initially and make sure everything works correctly.

Eventually, the documentation should cover the cookie authentication method with Swagger using CORS or web server.

**Comment by jamiltz** [comment]
The `enableCookies: true` option works with CORS which is pretty awesome! I'm going to add a note about this in the docs.

**Comment by Prudwell** [comment]
Yeah I think I'll wait before diving into reverse proxy stuff for now. 

I too got enableCookies working for CORS requests so I think authentication directly between browser and sync gateway will work until I see some reason that I really need a web server middleman. 

I'll keep an eye out for expanded documentation on this stuff, thanks for looking into these things!

**Comment by jamiltz** [comment]
Here's the updated docs http://developer.couchbase.com/documentation/mobile/1.3/develop/guides/authentication/custom-authentication/index.html#authentication-for-web-apps. But it only covers CORS for the moment.

**Comment by PaoloneM** [comment]
Landed here while dealing with [this problem](https://forums.couchbase.com/t/get-data-from-sync-gateway-with-syncgatewaysession-from-browser/19836/2).

Upvoted this feature request because I think that modern micro-services based systems could benefit of an extra authentication method like the "Authorization" header.
