### ISSUE TITLE
SG Swagger Spec Documentation for QUERY

### ISSUE THREAD

**Issue by Prudwell** [couchbaselabs/couchbase-mobile-portal#462]
Getting 403 forbiddens when trying to access the QUERY methods for the Public sync gateway endpoints and the swagger spec Implementation Notes aren't really telling me much about whether I'm using the API correctly. 

For methods like:
[put_db_design_ddoc](http://developer.couchbase.com/mobile/swagger/sync-gateway-public/#!/query/put_db_design_ddoc)
[get_db_design_ddoc](http://developer.couchbase.com/mobile/swagger/sync-gateway-public/#!/query/get_db_design_ddoc)

Is this on a per user basis, I.E. getting and setting design documents for the user whose credentials are being used in the request? I'm hitting these endpoints (gateway 1.3) with a valid session in a cookie and I have queries enabled in my sync_gateway.json file. I don't know where to look to see why I'm getting 403'd.

I've read through [Creating and querying a View ](http://developer.couchbase.com/documentation/mobile/1.3/develop/guides/sync-gateway/views/index.html) in the guides but it doesn't fully illuminate whether I can use public API to create views/design documents and on what scope those are available.

**[The setup that is generating 403s](https://gist.github.com/Prudwell/eac64a4d88733fce98f5becf5d09746e)**

Cheers!

**Comment by jamiltz** [comment]
It looks like the documentation is incorrect.

PUT, GET, DELETE /{db}/_design are on the admin interface since they are directly related to the query.

I updated the swagger spec and now they should appear on the [admin spec only](http://developer.couchbase.com/mobile/swagger/sync-gateway-admin/#/query). Can you try using the admin spec to persist the design doc and then use the public spec to query a view on it?

**Comment by Prudwell** [comment]
Ah that would explain the 403s. 

Was actually toying around with the admin endpoint last night and successfully did what you just described. A node script on the web server set a design document with a view via the admin port and my react browser code successfully queried the view via the public endpoint and swagger-client. The query returned only the current user's data as expected.

Cheers
