### ISSUE TITLE
Remove all_or_nothing from Sync Gateway REST API docs

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-mobile-portal#466]
In these docs:

http://developer.couchbase.com/documentation/mobile/current/develop/references/sync-gateway/rest-api/index.html

it mentions 

```
all_or_nothing: boolean
Indicates whether to use all-or-nothing semantics for the database commit mode
```

But according to this issue:

https://github.com/couchbase/sync_gateway/issues/1569

it's not supported.

**Comment by tleyden** [comment]
Looks like this has been commented out:

https://github.com/couchbaselabs/couchbase-mobile-portal/blob/f9da16e93153227af38b9942cccf335e2cec1a4a/docs/src/guides/sync-gateway/rest-apis/public-rest-api/database-resources/post-bulk-docs.xml#L38-L44

Just waiting for docs redeploy?  

Closing as done since it seems like that's the case, but re-open if not.

**Comment by tleyden** [comment]
Re-opening since I'm seeing it in the common area of the swagger spec:

https://github.com/couchbaselabs/couchbase-mobile-portal/blob/69fcb3d24b1b74246ce4ae3c552dfcbf214a82e7/swagger/paths/common.yaml#L53-L55

**Comment by jamiltz** [comment]
Hmm it was removed on 1.2 docs http://developer.couchbase.com/documentation/mobile/1.2/develop/references/sync-gateway/rest-api/database-public/post-bulk-docs/index.html

but not removed in swagger spec. And I should also remove the XML docs from master now. Yeah definitely needs fixing.

**Comment by jamiltz** [comment]
Updated in https://github.com/couchbaselabs/couchbase-mobile-portal/commit/83f32a4d559e1d63b8e01d2819194f2064636004
