### ISSUE TITLE
Add note to warn user against using developer.couchbase.com swagger spec in prod

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/couchbase-mobile-portal#470]

**Comment by Prudwell** [comment]
Ha I was about to put in a issue asking about this. In development I'm using the specs hosted on developer.couchbase.com and as they change, things keep breaking in my app that I have to go track down. **Is there any changelog for the specs that I can look at as things get updated?** For prod I'll definitely host the files myself but I'd like to stay up to date as things change during development.

Overall though I'm really liking using the swagger specs and swagger-client compared to building fetch queries by hand.

**Comment by jamiltz** [comment]
Sorry about the sudden update!

The specs were fine for the JS swagger client. But we've started experimenting with swagger codegen (the generator for native libraries) and changes were needed for strongly typed languages (again not that big of an issue for JS). But in doing that it changes some parameter names.

Out of curiosity how many changes did you end up making? There were lots of changes and I expect it to change again in a big way. I'll put together a change log as well this time.

Other than that, future changes should be smaller but we do need a change log as well. After googling I just found this https://github.com/civisanalytics/swagger-diff. It might help.

**Comment by Prudwell** [comment]
I've only got a few pieces using the swagger specs right now so I only needed to make 4 or so changes. In all cases it was due to a `body` field becoming something explicit like `SessionBody` or `Document`.

Thanks for the info on what's coming up!

Cheers
