### ISSUE TITLE
Add high-level documentation about tombstone management 

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/couchbase-mobile-portal#483]
Support has requested an overview-style document covering the recommended approach for managing obsolete tombstones (beyond what's already covered in the purge documentation).

This would include a discussion of purge and expiry, and also talk about the fact that purge/expiry needs to be done on both client- and server-side in order to avoid resurrection of tombstones.

**Comment by jamiltz** [comment]
@JFlath shared the link to the rev-tree pruning wiki https://github.com/couchbase/sync_gateway/wiki/Rev-Tree-Storage-on-Couchbase-Server#pruning. We should discuss the possibility of having a guide that covers rev tree pruning **and** single doc purging. What to use when? The differences..
