### ISSUE TITLE
Feedback for Training section

### ISSUE THREAD

**Issue by hideki** [couchbaselabs/couchbase-mobile-portal#491]
Notes for Training Section

1. Remove platforms of not officially supported. (All pages)
1. Update Design, Develop, Test, and Deploy pages. They just show list of child pages.
1. some of them use lower case "todo list", some use uppercase "ToDo List". Should be consistent.

#### Data Modeling:
1. Data Modeling: suggestion: separate List and Task table schema. it is confusing by both are in same table.
1. From Tables to JSON: `Couchbase Mobile stores data in documents`? What does it mean? `documents`?
1. Storing Dates: Font issue with `ISO-8601` string
1. Entity relationship: Why does `Task - list` contain "owner" field?

#### Access Control:
1.  Write Access: Texts in images are too small to read. <- Actually all images
1.  Write Access: Explain `List User` is joining `List` and `User`
1. Write Access: It is little hard to understand requireUser(...) method
1. Roles: `List`: Does not require to call requireRole("moderator")
1. Roles: Where does `moderator(s)`come from? Should it be `channel("moderator")`? 

#### Create a Database

1. `cd xcode-project/ios` for iOS
1. Open `Todo.xcworkspace` for iOS, as the project uses Cocoapod
1. Fix two warnings just after opening project file.
1. Create a new database: `<img src="img/image40.png" class="portrait" />` <<-- ??

#### Using the Database

1. Create a Document: Wrong error message
```
let docId = username + "." + NSUUID().uuidString
guard let doc = database.document(withID: docId) else {
    Ui.showMessageDialog(onController: self, withTitle: "Error",
        withMessage: "Couldn't save task list")
    return nil
}
```

#### Using Synchronization
1. Might need to explain GUEST mode is double negative. So GUEST mode is enabled.

#### Integration

1.  Bulk operations: By creating `Apple` task on iOS, Node prints folloing error.
```
TypeError: Cannot read property 'seq' of undefined
    at /Users/hideki/test/xcode-project/bot/app.js:56:38
    at _fulfilled (/Users/hideki/test/xcode-project/bot/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/hideki/test/xcode-project/bot/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/hideki/test/xcode-project/bot/node_modules/q/q.js:796:13)
    at /Users/hideki/test/xcode-project/bot/node_modules/q/q.js:604:44
    at runSingle (/Users/hideki/test/xcode-project/bot/node_modules/q/q.js:137:13)
    at flush (/Users/hideki/test/xcode-project/bot/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
1 change(s) received
```

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2923](https://issues.couchbase.com/browse/DOC-2923) and will get it fixed as soon as possible.
