### ISSUE TITLE
Sequence values should be documented as JSON, not integer

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/couchbase-mobile-portal#492]
Sequence values (since, last_seq, etc.) should be documented as JSON values, not integers.  They are intended to be opaque to clients.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2929](https://issues.couchbase.com/browse/DOC-2929) and will get it fixed as soon as possible.
