### ISSUE TITLE
random link not clickable under Routing/read access

### ISSUE THREAD

**Issue by raghusarangapani** [couchbaselabs/couchbase-mobile-portal#514]
I was going through the android tutorials at: 
http://developer.couchbase.com/documentation/mobile/1.3/training/develop/adding-security/index.html

Followed the exact steps for "Routing" and "Read Access".

The "random" button is not clickable. Given below is the console output for the page "http://localhost:4985/_admin/db/todo/sync" from Google chrome developer tools:

Download the React DevTools for a better development experience: https://fb.me/react-devtools
sync:580 binding routes
sync:569 [Mon Dec 12 2016 09:42:59 GMT-0800 (PST)] application started
sync:569 [Mon Dec 12 2016 09:42:59 GMT-0800 (PST)] runRoute: GET /_admin/db/todo/sync
sync:581 SyncFunEditor null Object {db: "todo"}
sync:581 SyncPreview Object {} Object {db: "todo"}
sync:580 doc async _role/admin
sync:580 doc async _role/moderator
sync:580 doc async _user/admin
sync:580 doc async _user/mod
sync:580 doc async _user/user1
sync:580 doc async _user/user2
sync:580 update rejected by sync function Object {name: "admin", all_channels: Array[1], _id: "_role/admin"} Object {channels: Array[0], access: Array[0], roles: Array[0], reject: Array[2]}
runSyncFunction @ sync:580
onChangeWDoc @ sync:580
(anonymous) @ sync:580
(anonymous) @ sync:579
on_end @ sync:579
on_state_change @ sync:579
sync:580 Uncaught TypeError: Cannot read property 'changed' of undefined
    at onChangeWDoc (sync:580)
    at sync:580
    at Object.callback (sync:579)
    at on_end (sync:579)
    at XMLHttpRequest.on_state_change (sync:579)
onChangeWDoc @ sync:580
(anonymous) @ sync:580
(anonymous) @ sync:579
on_end @ sync:579
on_state_change @ sync:579
sync:580 update rejected by sync function Object {name: "moderator", all_channels: Array[1], _id: "_role/moderator"} Object {channels: Array[0], access: Array[0], roles: Array[0], reject: Array[2]}
runSyncFunction @ sync:580
onChangeWDoc @ sync:580
(anonymous) @ sync:580
(anonymous) @ sync:579
on_end @ sync:579
on_state_change @ sync:579
sync:580 Uncaught TypeError: Cannot read property 'changed' of undefined
    at onChangeWDoc (sync:580)
    at sync:580
    at Object.callback (sync:579)
    at on_end (sync:579)
    at XMLHttpRequest.on_state_change (sync:579)
onChangeWDoc @ sync:580
(anonymous) @ sync:580
(anonymous) @ sync:579
on_end @ sync:579
on_state_change @ sync:579
sync:580 update rejected by sync function Object {name: "admin", all_channels: Array[1], admin_roles: Array[1], roles: Array[1], _id: "_user/admin"} Object {channels: Array[0], access: Array[0], roles: Array[0], reject: Array[2]}
runSyncFunction @ sync:580
onChangeWDoc @ sync:580
(anonymous) @ sync:580
(anonymous) @ sync:579
on_end @ sync:579
on_state_change @ sync:579
sync:580 Uncaught TypeError: Cannot read property 'changed' of undefined
    at onChangeWDoc (sync:580)
    at sync:580
    at Object.callback (sync:579)
    at on_end (sync:579)
    at XMLHttpRequest.on_state_change (sync:579)
onChangeWDoc @ sync:580
(anonymous) @ sync:580
(anonymous) @ sync:579
on_end @ sync:579
on_state_change @ sync:579
sync:580 update rejected by sync function Object {name: "mod", all_channels: Array[1], admin_roles: Array[1], roles: Array[1], _id: "_user/mod"} Object {channels: Array[0], access: Array[0], roles: Array[0], reject: Array[2]}
runSyncFunction @ sync:580
onChangeWDoc @ sync:580
(anonymous) @ sync:580
(anonymous) @ sync:579
on_end @ sync:579
on_state_change @ sync:579
sync:580 Uncaught TypeError: Cannot read property 'changed' of undefined
    at onChangeWDoc (sync:580)
    at sync:580
    at Object.callback (sync:579)
    at on_end (sync:579)
    at XMLHttpRequest.on_state_change (sync:579)
onChangeWDoc @ sync:580
(anonymous) @ sync:580
(anonymous) @ sync:579
on_end @ sync:579
on_state_change @ sync:579
sync:580 update rejected by sync function Object {name: "user1", admin_channels: Array[1], all_channels: Array[2], _id: "_user/user1"}_id: "_user/user1"admin_channels: Array[1]all_channels: Array[2]name: "user1"__proto__: Object Object {channels: Array[0], access: Array[0], roles: Array[0], reject: Array[2]}access: Array[0]channels: Array[0]reject: Array[2]roles: Array[0]__proto__: Object
runSyncFunction @ sync:580
onChangeWDoc @ sync:580
(anonymous) @ sync:580
(anonymous) @ sync:579
on_end @ sync:579
on_state_change @ sync:579
sync:580 Uncaught TypeError: Cannot read property 'changed' of undefined
    at onChangeWDoc (sync:580)
    at sync:580
    at Object.callback (sync:579)
    at on_end (sync:579)
    at XMLHttpRequest.on_state_change (sync:579)
onChangeWDoc @ sync:580
(anonymous) @ sync:580
(anonymous) @ sync:579
on_end @ sync:579
on_state_change @ sync:579
sync:580 update rejected by sync function Object {name: "user2", admin_channels: Array[1], all_channels: Array[2], _id: "_user/user2"} Object {channels: Array[0], access: Array[0], roles: Array[0], reject: Array[2]}
runSyncFunction @ sync:580
onChangeWDoc @ sync:580
(anonymous) @ sync:580
(anonymous) @ sync:579
on_end @ sync:579
on_state_change @ sync:579
sync:580 Uncaught TypeError: Cannot read property 'changed' of undefined
    at onChangeWDoc (sync:580)
    at sync:580
    at Object.callback (sync:579)
    at on_end (sync:579)
    at XMLHttpRequest.on_state_change (sync:579)
onChangeWDoc @ sync:580
(anonymous) @ sync:580
(anonymous) @ sync:579
on_end @ sync:579
on_state_change @ sync:579
localhost/:1 GET http://localhost:4985/favicon.ico/ 400 (Bad Request)

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to https://issues.couchbase.com/browse/DOC-2916 and will get it fixed as soon as possible.
