### ISSUE TITLE
Ports - SG to CB Server access

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/couchbase-mobile-portal#527]
From @househippo , moved from https://github.com/couchbase/sync_gateway/issues/2224:

> @sethrosetter / @jamiltz
> 
> Here is the link for the ports a APP can use to connect to Couchbase Server.
> https://developer.couchbase.com/documentation/server/current/install/install-ports.html
> 
> The "Node-to-client*" are the ports a typical JAVA or Node.js SDK would need.
> But since SG doesn't need:
> 8093 (N1QL)
> 18093 (SSL N1QL)
> 8094(Full Text Search)
> 
> the above can be block.
> 
> @jamiltz It be great to have some docs about needed ports for SG or add to the above page.
> 
> Thank you

**Comment by jamiltz** [comment]
@househippo added the list of ports and a link to the CBS Network Config page on the SG installation page.
