### ISSUE TITLE
2.0 DP docs

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/couchbase-mobile-portal#534]
The jenkins job is set up to monitor the 2.0 branch and make them available at [http://docs-build.sc.couchbase.com:4000/index.html](http://docs-build.sc.couchbase.com:4000/index.html).

@snej when possible, could you move the markdown content as it is from https://github.com/couchbase/couchbase-lite-ios/wiki/2.0-Developer-Preview-Notes to https://github.com/couchbaselabs/couchbase-mobile-portal/blob/2.0/md-docs/ready/guides/2.0-developer-preview.md

Any commit on the 2.0 branch will trigger the jenkins job. Markdown files can be edited on the GitHub UI similarly to wiki pages.

**Comment by snej** [comment]
Done!

**Comment by jamiltz** [comment]
Thanks! I re-added the front matter otherwise it doesn't get [rendered](http://docs-build.sc.couchbase.com:4000/2.0-developer-preview/index.html). Can you remove the Wiki to avoid duplicate content and to make sure the content gets updated in 1 place? I'll start looking into improving the layout etc.. but feel free to update the document as needs be.

**Comment by snej** [comment]
Deleted the wiki page.
