### ISSUE TITLE
make all installation pages follow the same content layout

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/couchbase-mobile-portal#557]
Todos:

- [x] Fix iOS page `h2`s.
- [x] Make the `available pods` and `frameworks` their own tables.
- [x] iOS: step to disable verbose logging by default.
- [x] iOS: step to disable app transport security.
- [x] iOS is missing the getting started code.
- [x] Android getting started code is incomplete.
- [x] Xamarin studio solution explorer screenshot.
- [x] .NET getting started code is incomplete.
- [x] .NET: remove `using a build from the CI server` section.
- ~~[ ] Java list of gradle dependencies.~~
- [x] Instructions to use Maven instead of JARs.
- [x] Java getting started code is incomplete.
- [x] Xamarin getting started is missing.
- [x] Java: list the maven packages.
- [x] PhoneGap getting started code is incomplete.
- [x] Find a way to run the app with and without credentials. This then helps to introduce the `phonegap serve --browser` command.
- [x] Credentials on android must be inserted in the request header. Workaround is to include a base64 encoding library.

**Comment by jamiltz** [comment]
@borrrden I'm trying to setup CBL in a Xamarin forms app. To which of the following projects should CBL be added? Can it be added to the common HelloCBL project or should it be added in both `.iOS` and `.Droid`?

![image](https://cloud.githubusercontent.com/assets/2589337/23185919/0e5aab42-f87d-11e6-827e-f9da95fd9284.png)

**Comment by jamiltz** [comment]
It got added to HelloCBL.iOS successfully

![image](https://cloud.githubusercontent.com/assets/2589337/23186256/5ce5ab62-f87e-11e6-84e0-2acd12e500bf.png)

Now I'm wondering how to access the CBL API from a shared project. Is that the way to do it?

**Comment by jamiltz** [comment]
I had setup Forms project with PCL. Started again with a Shared project and it works great on iOS.

When running on Android, the following is displayed:

<img src="https://cloud.githubusercontent.com/assets/2589337/23188673/8161a03c-f887-11e6-9fea-cfaf68e2b02a.png" width=25% />

@borrrden Is that something you've seen before?

**Comment by borrrden** [comment]
Yes, that message means you are using the system sqlite plugin, which is something you can no longer do.  1.4 has a custom sqlite plugin to get around this, and for earlier versions you can use sqlcipher instead.

**Comment by borrrden** [comment]
> Now I'm wondering how to access the CBL API from a shared project. Is that the way to do it?

Not directly.  See the discussion I had [here](https://github.com/couchbase/couchbase-lite-net/issues/818).  This is the reason things are set up with DI.

**Comment by jamiltz** [comment]
preview http://docs-build.sc.couchbase.com/mobile/557/installation/index.html
