### ISSUE TITLE
cross check SGA yaml config with source code

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/couchbase-mobile-portal#567]
The SGA config is extended from the SG config. Some properties from SG don't apply to SGA. That's why we need a separate page to document the SGA config alone. Some content might be duplicated but that's ok.

This ticket is created to mark the properties that apply to both SGA and SG. Then, the common properties will need to be copied from `configs/sg.yaml` to `configs/sg-accel.yaml`. The WIP is on https://github.com/couchbaselabs/couchbase-mobile-portal/tree/526-json-layout.

**Comment by jamiltz** [comment]
(FYI this is how the SGA config documentation is rendered based on the backing yaml file https://developer-stage.cbauthx.com/documentation/mobile/1.4/guides/sync-gateway/accelerator.html#story-h2-3)

**Comment by ajres** [comment]
These need validating but I think the following configuration properties are only utilised in SGA.

"cluster_config":{
    "server":"http://127.0.0.1:8091",
    "data_dir":".",
    "bucket":"data-bucket"
  }

      "channel_index":{
          "num_shards": 2
      }

**Comment by adamcfraser** [comment]
@ajres That set looks correct to me.  Just to clarify - the `channel_index` collection of parameters is used by both Sync Gateway and SGA - it's just the `num_shards` parameter that's exclusive to SGA.

**Comment by ajres** [comment]
@adamcfraser yes, agreed about num_shards.

I did come across this config property, which I thought was SGA but it does not seem to be used anywhere in the code base AFAIKS.

type ChannelIndexConfig struct {
	SequenceHashConfig *SequenceHashConfig `json:"seq_hashing,omitempty"` // Sequence hash configuration
}

**Comment by adamcfraser** [comment]
The SequenceHashConfig is actually Sync Gateway only, but you're right, it's not used yet.  There's a pending enhancement to support using a separate bucket for sequence hash storage, but it's still in the backlog.

**Comment by ajres** [comment]
These are the properties appear to be only relevant for Sync Gateway:

Top Level
{
  Interface
  SSLCert 
  SSLKey
  ServerReadTimeout
  ServerWriteTimeout
  AdminInterface
  AdminUI    
  ProfileInterface
  ConfigServer
  Facebook 
  Google
  CORS
  MaxIncomingConnections
  CompressResponses
  Replications
  MaxHeartbeat
}

database {
  Sync
  Users
  Roles
 RevsLimit 
 ImportDocs 
 Shadow 
 EventHandlers
 FeedType
 AllowEmptyPassword
 CacheConfig 
 ChannelIndex
 RevCacheSize
 StartOffline
 OIDCConfig
 Unsupported
}

**Comment by jamiltz** [comment]
> Just to clarify - the channel_index collection of parameters is used by both Sync Gateway and SGA - it's just the num_shards parameter that's exclusive to SGA.

@adamcfraser are there any properties in `channel_index` used by SG currently? Just curious, I don't see any in the docs.

**Comment by adamcfraser** [comment]
The `channel_index` property specifies the index bucket that Sync Gateway uses when running in a cluster with SGA.  It includes the BucketConfig interface, and so has the full set of parameters used for normal bucket connection (server/pool/bucket/username/password).

**Comment by ajres** [comment]
@adamcfraser can you sanity check the list of SG only properties above to see if there are any inclusions or ommissions that need fixing.

**Comment by adamcfraser** [comment]
@ajres I crossed out a few items on the list above that **are** used by SGA.  The rest look good.
