### ISSUE TITLE
SG: doc channel limit or performance impact of adding channels

### ISSUE THREAD

**Issue by djpongh** [couchbaselabs/couchbase-mobile-portal#573]
Is there a hard limit on the number of channels that can be created in Sync Gateway? A customer expects to create more than 1 million.
If there are no hard limits are there any expected performance hits? For example a background process that runs through the list of channels to do some work, would a large number of channels potentially create an issue?
Is there a limit to the number of channels a user can subscribe to?
Would a large number of channel subscription possibly cause some type of performance issues for that specific user, during syncs etc?

For example:
solution A. 
There are 1 million documents, distributed across 200 channels, with 10k users subscribed to the various channels. 
solution B.
There is 1 million documents, distributed across 1 million channels (each doc in its own channel), and 10K users subscribed to those various channels.
Would solution B introduce a significant more amount of overhead/performance issues then solution A?

CBSE-3433

**Comment by jamiltz** [comment]
https://issues.couchbase.com/browse/CBSE-3433

**Comment by jamiltz** [comment]
Few answers in the google groups:

- https://groups.google.com/forum/#!searchin/mobile-couchbase/sync$20gateway$20channels|sort:relevance/mobile-couchbase/dIyAu3JAIQM/zks1aNAeAgAJ
- https://groups.google.com/forum/#!searchin/mobile-couchbase/sync$20gateway$20channels|sort:relevance/mobile-couchbase/T84kt-4v880/DPAJ6s4_LQUJ

The content should live on the Data Routing page https://developer.couchbase.com/documentation/mobile/1.3/guides/sync-gateway/channels/index.html in the **developing channels** section.
