### ISSUE TITLE
How to monitor Sync Gateway?

### ISSUE THREAD

**Issue by ssmotra** [couchbaselabs/couchbase-mobile-portal#583]
Need to add more details on how SG should be monitored. 

- Cover monitoring solutions that we have integrated with.

- Examples of how to retrieve monitoring data from SG.

**Notes from Adam's email below** 
the Sync Gateway diagnostics endpoint -  "/_expvar" on the Admin REST API -  is also a useful source of diagnostic information for a running Sync Gateway, including memory stats and number of active connections among others.  It returns a JSON format that can be integrated into multiple consumers – it's the raw material we use for a lot of the metrics on our performance dashboard.  The emphasis of the _expvar endpoint has been primarily internal thus far – we've been more focused on the information we need for performance monitoring, as opposed to specific customer diagnostic requirements - but there's a lot of generally useful information in there.  I've attached sample output.
 
On the logs side - monitoring the logs for warnings, errors and panics would make sense.  Warnings and errors have a standard format in the logs that they could use as a filter.  Lower level log analysis for things like operation round trip times or operations by user would be possible using the HTTP+ log key, but that's usually more useful for issue investigation, versus ongoing monitoring.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2920](https://issues.couchbase.com/browse/DOC-2920) and will get it fixed as soon as possible.
