### ISSUE TITLE
getting started mock up

### ISSUE THREAD

**Issue by ssmotra** [couchbaselabs/couchbase-mobile-portal#618]
- I followed the steps for "getting started" and could not figure out how to create a simple application

- The instructions on the "getting started" page are incomplete. They don't walk through the process of creating an app and running it.

- The tutorial has the steps to create the "to-do" application. These need to be combined into one getting started page.

**Comment by jamiltz** [comment]
@ssmotra could you try this one? http://couchbase-docs.s3.amazonaws.com/mobile/branches/557/installation/android/index.html#getting-started

**Comment by ssmotra** [comment]
- We need to re-use the example used in the tutorial.
- Remove all references to sync gateway and replication from the getting started example
- Rename "getting started" in the page content to "running your first example"
- Start with an outline of what you are going to do to get started

**Comment by ssmotra** [comment]
- Add all gradle dependencies in step 3 of the gradle section and remove the table with others. Add text at the bottom to let users know that they are including all dependencies and will be using different libraries as new functionality gets added.

**Comment by jamiltz** [comment]
> Add all gradle dependencies in step 3 of the gradle section and remove the table with others. Add text at the bottom to let users know that they are including all dependencies and will be using different libraries as new functionality gets added.

The downside with doing this is that it will increase the size of the app unnecessarily. If we teach users to include everything they might forget about it in a production app and then ask why the app size is so high.

**Comment by jamiltz** [comment]
- [x] rename getting started to running your first example

**Comment by jamiltz** [comment]
From @ssmotra's email:

- Getting Started
- iOS
  - Installing CB Lite
  - Creating a document
  - Install SG
  - Configure Replication
- Android
  - Installing CB Lite
  - Creating a document
  - Install SG
  - Configure Replication

**Comment by jamiltz** [comment]
https://issues.couchbase.com/browse/DOC-2871
