### ISSUE TITLE
Sync Gateway replication caveat: users aren't sync'd

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-mobile-portal#624]
Sync gateway replication doesn't sync users -- this should be mentioned as a rather glaring caveat (maybe a warning icon) near this statement:

> "On the architecture diagram below, any changes that users/systems make on either Sync Gateway instance will be replicated to the other Sync Gateway instance."

**Comment by jamiltz** [comment]
@tleyden can you clarify in which scenario this is the case:

1. If a user is defined in the config file of SG 1 then it won't be replicated to SG 2?
2. If a user is defined through the REST API of SG 1 then it won't be replicated to SG 2?

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2949](https://issues.couchbase.com/browse/DOC-2949) and will get it fixed as soon as possible.
