### ISSUE TITLE
Update 2.0 Query API documentationb

### ISSUE THREAD

**Issue by pasin** [couchbaselabs/couchbase-mobile-portal#625]
The Query API section in https://developer.couchbase.com/documentation/mobile/2.0/couchbase-lite/ios.html needs to be updated for DB3 as we start to rollout the cross platform query API.
 
I have started the documentation. Could you please revise and edit the documentation at least the following topics:
 
1. CBLQueryExpression (I do not know how do we come up with the list of the expression).
 
2. The co-exist of CBLQuery and CBLPredicate Query

[Query.md.zip](https://github.com/couchbaselabs/couchbase-mobile-portal/files/856603/Query.md.zip)

**Comment by jamiltz** [comment]
- created a follow up ticket for the first point https://github.com/couchbaselabs/couchbase-mobile-portal/issues/627
- second point falls under the "platform specific docs vs cross platform docs" issue which is covered in https://github.com/couchbaselabs/couchbase-mobile-portal/issues/609
