### ISSUE TITLE
document the list of expressions CBLQueryExpressions

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/couchbase-mobile-portal#627]
@pasin do we have a list of the possible expression? (in a wiki, spec file or source code file)

**Comment by pasin** [comment]
Here is the full list of the expression that we plan to support.

https://github.com/couchbaselabs/couchbase-lite-apiv2/blob/master/query/objc/CouchbaseLiteQuery/CBLQueryExpression.h

**Comment by jamiltz** [comment]
a possibility might be to link to [this page](http://docs.couchbase.com/mobile/2.0/couchbase-lite-objc/db003/Classes/CBLQueryExpression.html) from the guide page.

**Comment by jamiltz** [comment]
@pasin can you point me to an ObjC unit test of the cross platform query api?

**Comment by jamiltz** [comment]
Found an example, I just realized it is in the doc updates you made last week.
