### ISSUE TITLE
transactions code example

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/couchbase-mobile-portal#641]

**Comment by borrrden** [comment]
The API is called "InBatch" now, as it doesn't have every transactional guarantee of an ACID storage system.

https://github.com/couchbase/couchbase-lite-net/blob/feature/api-v2/src/Couchbase.Lite.Tests.Shared/DocumentTest.cs#L616 .NET

**Comment by jamiltz** [comment]
done on 2.0
