### ISSUE TITLE
fts code example

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/couchbase-mobile-portal#645]

**Comment by jamiltz** [comment]
all 3

**Comment by borrrden** [comment]
https://github.com/couchbase/couchbase-lite-net/blob/feature/api-v2/src/Couchbase.Lite.Tests.Shared/QueryTest.cs#L470 .NET

**Comment by pasin** [comment]
**NSPredicate**
https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/Tests/PredicateQueryTest.m#L170-L187

**Crossplatform API**
https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Swift/Tests/QueryTest.swift#L254-L272
https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Swift/Tests/QueryTest.swift#L254-L272

**Comment by jamiltz** [comment]
done on the 2.0 branch.
