### ISSUE TITLE
conflict resolution guide

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/couchbase-mobile-portal#655]
issues were found in this guide https://developer.couchbase.com/documentation/mobile/1.4/guides/sync-gateway/resolving-conflicts/index.html?language=ios

review conflict resolution guide, with `revs_limit: 3` in the config.

1. does it return 3 as the number of parent revisions.
2. on the client does running a compaction remove the tombstones.

**Comment by jamiltz** [comment]
From @househippo 

> the Node.js script expects the document to have a particular type. the script below cleans up obsolete conflicting revisions only and doesn't require a specific schema.

[find_conflicts.py.zip](https://github.com/couchbaselabs/couchbase-mobile-portal/files/935719/find_conflicts.py.zip)

It would be good to have both scenarios in the resolving conflicts guide (1. the default always wins and 2. custom resolution based on the document type).

**Comment by Fujio-Turner** [comment]
@jamiltz  , here is the "official" repo of the find_confilcts.py
https://github.com/Fujio-Turner/sg-find-conflict-demo
