### ISSUE TITLE
Android Tutorial - Emulator launch with Docker

### ISSUE THREAD

**Issue by ssmotra** [couchbaselabs/couchbase-mobile-portal#661]
Here is some feedback from a customer regarding the Android tutorial. Please add a call out for the emulator launch with Docker. 

> I’ve started doing Android development with Couchbase and wanted to send a suggestion for your Android development tutorial. The Android emulator images typically default to x86 which use HAXM hardware acceleration. Unfortunately, if you’re running Couchbase in Docker on your development machine, the emulator won’t launch. It took some sleuthing to figure out that Docker + x86 Android images cause the Android emulator launch to silently fail.
>  
> It would be great to have a callout in the Android tutorial that says: “If you’re using an emulator, run ARM images as docker + x86 images aren’t compatible” or “If you’re using a real device, use port forwarding on ADB to connect to a CB server running on your development machine”

**Comment by jamiltz** [comment]
Yes that makes total sense, have run into this issue myself many times and forgot that Docker was running in the background. I think the place that could be added is as a bulleted item in the [Requirements](https://developer.couchbase.com/documentation/mobile/1.4/training/develop/create-database/index.html?language=android#requirements) section on each page, possible with a warning icon (⚠️). Let me know if you were thinking of somewhere else on the page. Will be scheduled for the next sprint.

**Comment by jamiltz** [comment]
note added to every page under develop:
- https://developer.couchbase.com/documentation/mobile/1.4/training/develop/create-database/index.html?language=android#requirements
- https://developer.couchbase.com/documentation/mobile/1.4/training/develop/using-the-database/index.html?language=android
- https://developer.couchbase.com/documentation/mobile/1.4/training/develop/adding-synchronization/index.html?language=android
- https://developer.couchbase.com/documentation/mobile/1.4/training/develop/adding-security/index.html?language=android
-
 https://developer.couchbase.com/documentation/mobile/1.4/training/develop/integration/index.html?language=android
