### ISSUE TITLE
Add Carthage instructions to 2.0 release notes

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-mobile-portal#665]
When I search https://github.com/couchbaselabs/couchbase-mobile-portal/blob/2.0/md-docs/_20/couchbase-lite/ios.md for Carthage, I don't see any mention.

(also see email thread with @djpongh titled "Carthage instructions for couchbase lite 2.0")

**Comment by jamiltz** [comment]
https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/index.html?language=swift
