### ISSUE TITLE
Missing docs for updateIndexAsync on Cblite java platform

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-mobile-portal#681]
From @Martin-Hogge in https://github.com/couchbase/couchbase-lite-ios/issues/1010#issuecomment-296972275

> Hi, I correctly see the updateIndex reference on the official doc but none for the updateIndexAsync. I could run the updateIndex method on a background thread myself but if an async method exists it would be easier to directly use it.

> Plus, I do not see it in the official documentation but I find out that their is an updateIndexAlone method on the CBLite sdk. I'm not sure to understand correctly the difference between updateIndex and updateIndexAlone. Here is its JavaDoc:

```
/**
* Updates the view's index (incrementally) if necessary.
* Only the view's index alone will be updated.
*
* @return Status OK if updated or NOT_MODIFIED if already up-to-date.
* @throws CouchbaseLiteException
*/
```

**Comment by tleyden** [comment]
@hideki can you confirm that `updateIndexAsync` is supported in Couchbase Lite Java?

**Comment by carrotalan** [comment]
Also missing in the iOS API documentation
