### ISSUE TITLE
Upgrade docs should cover all platforms where possible

### ISSUE THREAD

**Issue by JFlath** [couchbaselabs/couchbase-mobile-portal#688]
Although a lot of the advice is applicable, our steps here are focused on CentOS/RHEL - given that we have the ability to insert tabbed code blocks, it would be nice to cover other platforms too.

**Comment by jamiltz** [comment]
yes code tabs is a good choice here. Which page in the docs are you referring to?

**Comment by JFlath** [comment]
Sorry, forgot to add that:
https://developer.couchbase.com/documentation/mobile/1.4/training/deploy/upgrade/index.html

There's a good chance we'll get a direct contribution on this one, so I'd hold fire for now if that's okay?

**Comment by jamiltz** [comment]
Ok sounds good. I'm just thinking about the code tabs and how to make it work, it'll be nice to use them in this part of the docs.

**Comment by benjaminglatzeder** [comment]
Hi, I was in touch with @JFlath 

I wrote this guide, maybe it helps others too.

**Guide to update Sync Gateway (SG) on Ubuntu 14.04 TLS with no downtime**  
- [Prerequisites](#prerequisites)
- [On Load balancer](#on-load-balancer)
  * [Disable traffic for one SG](#disable-traffic-for-one-sg)
- [On SG node](#on-sg-node)
  * [Check SG version](#check-sg-version)
  * [Download package](#download-package)
  * [Stop SG](#stop-sg)
  * [Remove SG package](#remove-sg-package)
  * [Install package](#install-package)
  * [Check SG status, version and config](#check-sg-status--version-and-config)
  * [Remove downloaded package (optional)](#remove-downloaded-package--optional-)
- [On Load balancer](#on-load-balancer-1)
  * [Enable traffic](#enable-traffic)
- [Troubleshoot](#troubleshoot)
# Prerequisites
* nginx is used as load balancer in front of SG nodes
* python -m json.tool for nicer output (optional)  

**Start here and repeat for all SG nodes one at a time**  

# On Load balancer  
## Disable traffic for one SG  
Open your nginx config, e.g.  
`vim /etc/nginx/sites-available/sync_gateway`  

add `down` at the end of upstream entry, save and quit

E.g. 

```bash
upstream my_couchbase_database {  
    ip_hash;  
    server <IP-of-SG1>:4984 down; #SG1  
    server <IP-of-SG1>:4984; #SG2  
}
```

test and reload nginx config
```bash

nginx -t

nginx -s reload
```

# On SG node
## Check SG version  

```bash
curl http://localhost:4984 | python -m json.tool
```


## Download package
Go to [https://www.couchbase.com/downloads](Link URL), then download md5 file and replace last part with what's in the file and version no

```bash
wget http://packages.couchbase.com/releases/couchbase-sync-gateway/<version no>/<build name in md5 file>

wget http://packages.couchbase.com/releases/couchbase-sync-gateway/1.4.0/couchbase-sync-gateway-enterprise_1.4.0-2_x86_64.deb
```


## Stop SG
```bash
service sync_gateway stop
```
## Remove SG package
```bash
sudo apt-get remove couchbase-sync-gateway

apt-get autoremove # if necessary
``` 

## Install package  
```bash
sudo dpkg -i <build name in md5 file>

sudo dpkg -i couchbase-sync-gateway-enterprise_1.4.0-2_x86_64.deb
```
## Check SG status, version and config
```bash
service sync_gateway status

curl http://localhost:4984 | python -m json.tool

curl -X GET http://localhost:4985/<my_couchbase_database>/_config | python -m json.tool
```

## Remove downloaded package (optional) ##

```bash
rm couchbase-sync-gateway-enterprise_1.4.0-2_x86_64.deb # WARNING: Check command before deleting unwanted files
```

# On Load balancer
## Enable traffic 
`vim /etc/nginx/sites-available/sync_gateway`  

remove down at the end of upstream entry, save and quit

E.g. 

```bash
upstream my_couchbase_database {  
    ip_hash;  
    server <IP-of-SG1>:4984; #SG1  
    server <IP-of-SG1>:4984; #SG2  
}
```

# Troubleshoot
```bash
# Restart SG
service sync_gateway restart
# Check error log
tail -n 100 /home/sync_gateway/logs/sync_gateway_error.log
# Check SG config
vim /home/sync_gateway/sync_gateway.json
```

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to https://issues.couchbase.com/browse/DOC-2872 and will get it fixed as soon as possible.
