### ISSUE TITLE
Sync Gateway DELETE requires a rev

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/couchbase-mobile-portal#693]
According to the docs (https://developer.couchbase.com/documentation/mobile/current/references/sync-gateway/rest-api/index.html#!/document/delete_db_doc), a rev is optional when deleting a doc.

A rev is required.

**Comment by jamiltz** [comment]
fixed in https://github.com/couchbaselabs/couchbase-mobile-portal/issues/742
