### ISSUE TITLE
add content from blog on conflict resolution to docs 

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-mobile-portal#695]
This came out of a question from @rajagp about conflict resolution.

In the docs:

1. The winner is the undeleted leaf revision on the longest revision branch. This would be the Revision Id with the largest prefix number.
1. If there are no undeleted leaf revisions, the deletion on the longest branch wins. 
1. If there's a tie, the winner is the one whose Revision Id sorts higher in a simple ASCII comparison.

and I think we should include some diagrams that reinforce these points.  Here are some rough drafts, and I'll try to get these nicer looking in Omnigraffle or something.

## 1. The winner is the undeleted leaf revision on the longest revision branch. This would be the Revision Id with the largest prefix number.

![img_1433](https://cloud.githubusercontent.com/assets/296876/25767338/2964580c-31ad-11e7-9d48-529a580990b7.JPG)

## 2. If there are no undeleted leaf revisions, the deletion on the longest branch wins. 

![img_1434](https://cloud.githubusercontent.com/assets/296876/25767349/3984cf14-31ad-11e7-9d01-5af2ea5429c3.JPG)

## 3. If there's a tie, the winner is the one whose Revision Id sorts higher in a simple ASCII comparison.

![img_1435](https://cloud.githubusercontent.com/assets/296876/25767360/4b5612fc-31ad-11e7-83b2-8e370d42c086.JPG)

**Comment by tleyden** [comment]
@rajagp your question as I understand it was "If I have deleted and undeleted revisions as leaf nodes and the leaf node in the longest branch is deleted, then which branch is considered the winning branch"

That sounds like this scenario:

![img_1436](https://cloud.githubusercontent.com/assets/296876/25767382/90b8788a-31ad-11e7-9570-3c36e15ea7e1.JPG)

so basically even though the 1-xyz -> 2-cbd branch is shorter, since it's the longest *undeleted* branch, it's the winning branch.

**Comment by rajagp** [comment]
Excellent @tleyden - this answers my question.  Reg drawings- that's exactly what I had in mind for my upcoming blog post on demystifying conflict resolution. So lot of pretty pictures coming up !

**Comment by jamiltz** [comment]
> In the docs:
> - The winner is the undeleted leaf revision on the longest revision branch. This would be the Revision Id with the largest prefix number.
> - If there are no undeleted leaf revisions, the deletion on the longest branch wins.
> - If there's a tie, the winner is the one whose Revision Id sorts higher in a simple ASCII comparison.

@tleyden where did you find this in the docs? can't find it and if it's missing from it then we should re-open the ticket to add it.

**Comment by tleyden** [comment]
I'm still going to re-open this because the current official docs could use some improvement, in particular some visuals
