### ISSUE TITLE
Improve SG _purge API documentation

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/couchbase-mobile-portal#698]
The payload for the purge API doesn't make it clear that the request body needs to be of the form:

{
  "a_doc_id": [
    "*"
  ],
}

i.e. that `*` is the only valid value for the revision property (currently shown in the docs as just 'string'.

**Comment by jamiltz** [comment]
Added an enum property with a single value. Swagger UI now shows `"*"` as the only possible value.

![image](https://user-images.githubusercontent.com/2589337/27918813-f8dfb1c2-6267-11e7-8809-8a52f96c1df5.png)
