### ISSUE TITLE
Certificate pinning in Couchbase Lite

### ISSUE THREAD

**Issue by ssmotra** [couchbaselabs/couchbase-mobile-portal#710]
Include details on how to use pinned certificate with Couchbase Lite in the documentation. The docs should include a code sample as well.

**Comment by jamiltz** [comment]
High level definition

> SSL Pinning is making sure the client checks the server’s certificate against a known copy of that certificate. Simply bundle your server’s SSL certificate inside your application, and make sure any SSL request first validates that the server’s certificate exactly matches the bundle’s certificate.

[source](https://possiblemobile.com/2013/03/ssl-pinning-for-increased-app-security/)

Couchbase Lite iOS cert pinning page https://github.com/couchbase/couchbase-lite-ios/wiki/SSL
[setAnchorCerts:](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/API/CBLReplication.h#L150)

**Comment by jamiltz** [comment]
This content could go on the `Guides > Couchbase Lite > Native API > Replication` page. Need to make it clear it's iOS only at this point.

**Comment by jamiltz** [comment]
additional link https://github.com/couchbase/couchbase-lite-ios/wiki/Replication-Custom-Properties

**Comment by rajagp** [comment]
@jamiltz  Can we include a link to this blog ?  https://blog.couchbase.com/certificate-pinning-couchbase-mobile-ios-app/ (CC @ssmotra )

**Comment by rajagp** [comment]
What was the resolution on my comment above?

**Comment by jamiltz** [comment]
It moved to https://issues.couchbase.com/browse/DOC-2867. Sorry, should have posted a message.

**Comment by rajagp** [comment]
Ah. OK. So that explains why all the GitHub  tickets were closed. (Understand. It's a bit tedious - but  would be good to show the including ticket in JIRA so the reporters can track the issues they filed)

**Comment by jamiltz** [comment]
Yep, there was a problem with the issue importer yesterday so some tickets were closed without a comment. And some were closed with a comment like https://github.com/couchbaselabs/couchbase-mobile-portal/issues/115. I'm triaging all of them now and will post a comment to those that didn't get it.
