### ISSUE TITLE
Sync Gateway Admin REST API _replicate docs don't mention "changes_feed_limit" param

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-mobile-portal#721]
In [these docs](https://developer.couchbase.com/documentation/mobile/current/references/sync-gateway/admin-rest-api/index.html#!/server/post_replicate) it doesn't mention the `changes_feed_limit` parameter.   

I just tested it and it works:

```
{
  "create_target": false,
  "source": "http://localhost:4985/source",
  "target": "http://localhost:4987/target",
  "changes_feed_limit": 100,
  "replication_id": "one-way-continuous"
}
``` 

The param is documented here: https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/config-properties/index.html under **replications[] configuration**

**Comment by jamiltz** [comment]
The description was also missing on the config properties page so I added it there as well.
