### ISSUE TITLE
users in SG and CB when using xattrs

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/couchbase-mobile-portal#728]
User creation for mobile users – why? How are these different from server users?

SG users are application users. Different RBAC users.

If the sync function rejects the document the SDK write will still return as being successful. Same thing as if the doc wasn't mobile enabled.

A /_resync will reprocess the existing docs.

**Comment by agonyou** [comment]
When users are created via couchbase server, can those users be used in mobile too? (i.e. single unified user store?)

**Comment by agonyou** [comment]
also can roles be inherited?

**Comment by jamiltz** [comment]
@agonyou we've tried to answer those questions in this commit https://github.com/couchbaselabs/couchbase-mobile-portal/commit/205c63570dec7842035c5f5ebeb741eeb82aea95

Feel free to comment back here if there's anything that's missing or unclear. Thanks!
