### ISSUE TITLE
Document limit on the number of channels that can be created in Sync Gateway and any performance implications

### ISSUE THREAD

**Issue by djpongh** [couchbaselabs/couchbase-mobile-portal#733]
Is there a hard limit to the number of channels that can be created? Is there a hard limit to how many channels a single user can subscribe to? Assuming there is not, what would be the expected performance impact of this?
For example:
solution A. 
There are 1 million documents, distributed across 200 channels, with 10k users subscribed to the various channels. 
solution B.
There is 1 million documents, distributed across 1 million channels (each doc in its own channel), and 10K users subscribed to those various channels.
Would solution B introduce a significant more amount of overhead/performance issues then solution A?

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2858](https://issues.couchbase.com/browse/DOC-2858) and will get it fixed as soon as possible.
