### ISSUE TITLE
Document the ratio of number of cbs to sg 

### ISSUE THREAD

**Issue by raghusarangapani** [couchbaselabs/couchbase-mobile-portal#736]
Filing this issue on behalf of @suravarjjala 

There is no recommended configuration documentation of how many couchbase servers are needed per sync gateway or how many sync gateways can be handled by a server. This is a tracking ticket to add this info to the documentation.

**Comment by jamiltz** [comment]
moved to https://issues.couchbase.com/browse/DOC-2868
