### ISSUE TITLE
CBL: Need documentation on background apps

### ISSUE THREAD

**Issue by mattcarabine** [couchbaselabs/couchbase-mobile-portal#738]
From https://issues.couchbase.com/browse/DOC-2491

---

There's no documentation on what to expect when an application is backgrounded on various platforms.  For instance, I believe that Sync stops unless it is manually called with a trigger from a push notification or manually called.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2880](https://issues.couchbase.com/browse/DOC-2880) and will get it fixed as soon as possible.
