### ISSUE TITLE
Mark SG Admin UI as beta

### ISSUE THREAD

**Issue by djpongh** [couchbaselabs/couchbase-mobile-portal#739]
To avoid customer confusion, we need to clearly mark the Sync Gateway Admin UI as beta / unsupported.

**Comment by djpongh** [comment]
Perhaps a note similar to what's done for FTS:
 https://developer.couchbase.com/documentation/server/current/fts/full-text-intro.html

**Comment by djpongh** [comment]
Including: https://developer.couchbase.com/documentation/mobile/1.4/guides/sync-gateway/config-properties/index.html

**Comment by jamiltz** [comment]
dup https://github.com/couchbaselabs/couchbase-mobile-portal/issues/749
