### ISSUE TITLE
PUT endpoint to create conflicts does not work as described in docs

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-mobile-portal#743]
Steps to repro:

1.  POST to `http://{{host}}:{{port_admin}}/{{db}}/`, which returns

```
{
    "id": "7a1d21a15c5873441217eb5f62af46c3",
    "ok": true,
    "rev": "1-ecbd22495c41163e3657699fd1f5ca28"
}
```

1. PUT to `http://{{host}}:{{port_admin}}/{{db}}/7a1d21a15c5873441217eb5f62af46c3`, which returns

```
{
    "id": "7a1d21a15c5873441217eb5f62af46c3",
    "ok": true,
    "rev": "2-9751b0b11d5cbeae6d9d756603b4cdc2"
}
```

1. Try to create conflict rev by doing a PUT to `http://{{host}}:{{port_admin}}/{{db}}/7a1d21a15c5873441217eb5f62af46c3?new_edits=false` with a body:

```
{
  "key": "val 2b",
  "_rev": "1-ecbd22495c41163e3657699fd1f5ca28"
}
```

That returns:

```
{
    "id": "7a1d21a15c5873441217eb5f62af46c3",
    "ok": true,
    "rev": "1-ecbd22495c41163e3657699fd1f5ca28"
}
```

instead of a different revision with generation 2.

I also tried to create conflict rev by doing a PUT to `http://{{host}}:{{port_admin}}/{{db}}/7a1d21a15c5873441217eb5f62af46c3?new_edits=false&rev=1-ecbd22495c41163e3657699fd1f5ca28` with a body:

```
{
  "key": "val 2b"
}
```

in that case I get:

```
{
    "error": "Bad Request",
    "reason": "Bad _revisions"
}
```

**Comment by tleyden** [comment]
The docs I'm looking at:

https://developer.couchbase.com/documentation/mobile/1.4/references/sync-gateway/admin-rest-api/index.html#!/document/put_db_doc

**Comment by tleyden** [comment]
Somewhat related, but in the [post_db_bulk_docs](https://developer.couchbase.com/documentation/mobile/1.4/references/sync-gateway/admin-rest-api/index.html#!/database/post_db_bulk_docs) endpoint, it doesn't describe the `_revisions` property (see the [couchdb equivalent docs](https://wiki.apache.org/couchdb/HTTP_Bulk_Document_API#Posting_Existing_Revisions) for a description)

**Comment by tleyden** [comment]
Continuing the above example in the original comment, using `_revisions` in conjunction with `PUT /db/doc` works.

```
PUT http://{{host}}:{{port_admin}}/{{db}}/7a1d21a15c5873441217eb5f62af46c3?new_edits=false
```

with body:

```
{
   "key":"val 2b",
   "_revisions":{
      "start":2,
      "ids":[
         "3595405",
         "ecbd22495c41163e3657699fd1f5ca28"
      ]
   }
}
```

results in a new conflicting revision:

```
{
    "id": "7a1d21a15c5873441217eb5f62af46c3",
    "ok": true,
    "rev": "2-3595405"
}
```

**Comment by tleyden** [comment]
Here are curl examples to add conflicts via `PUT` requests:

https://github.com/couchbase/sync_gateway/issues/2651#issuecomment-309916861

**Comment by jamiltz** [comment]
@tleyden Thanks for curls! see the commit above. Do you know if the `_revisions` structure is the same in `/{db}/{id}` and `/{db}/_bulk_docs`? If so, [this line](https://github.com/couchbaselabs/couchbase-mobile-portal/commit/067cdaf4b1042d4bebf29e339c27d7297716f1c7#diff-e70879af73c59c8a4b1ee921c169364fR12) takes care of reusing the Document definition. Otherwise the spec might need further changes.

**Comment by tleyden** [comment]
I believe we still need to remove the `rev` parameter.  Re-opening as a reminder to investigate.

**Comment by tleyden** [comment]
> Do you know if the _revisions structure is the same in /{db}/{id} and /{db}/_bulk_docs

Yep, it is

**Comment by jamiltz** [comment]
> I believe we still need to remove the rev parameter.

Isn't that needed when creating a non-conflicting revision?

**Comment by tleyden** [comment]
Yeah, you're right.  There's another confusing thing about rev, but I'll create a separate issue
