### ISSUE TITLE
Call out that SG admin UI is an experimental feature 

### ISSUE THREAD

**Issue by ssmotra** [couchbaselabs/couchbase-mobile-portal#749]
All references to the SG admin UI in the docs portal need to call out the fact that it is an experimental feature. Experimental features may have bugs since they are not certified by Couchbase QE. Couchbase may drop the feature all together or create a brand new component with equivalent functionality in new releases.

**Comment by jamiltz** [comment]
references to admin UI in docs:

- https://developer.couchbase.com/documentation/mobile/1.4/installation/sync-gateway/index.html#getting-started
- https://developer.couchbase.com/documentation/mobile/1.4/training/develop/adding-security/index.html

**Comment by jamiltz** [comment]
@ssmotra the links above now include a callout on the left. Let me know if there's anything else that should be done for this.
