### ISSUE TITLE
SG REST API - PUT request should mention that rev param can be either in json or query

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-mobile-portal#752]
In https://developer.couchbase.com/documentation/mobile/current/references/sync-gateway/rest-api/index.html#!/document/put_db_doc there are two ways to mention the `rev` parameter:

1. Query
1. JSON body

I think it should be mentioned that either way is valid, and what happens if *different* values are provided -- which takes precedence?  Will an error be thrown?

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2859](https://issues.couchbase.com/browse/DOC-2859) and will get it fixed as soon as possible.
