### ISSUE TITLE
Remove references to ForestDB in docs

### ISSUE THREAD

**Issue by ssmotra** [couchbaselabs/couchbase-mobile-portal#755]
We need to remove all references to "forestDB" in our documentation since that is not the preferred storage option anymore.

**Comment by jamiltz** [comment]
@ssmotra there is currently a note in the docs advising not to use ForestDB https://developer.couchbase.com/documentation/mobile/1.4/guides/couchbase-lite/native-api/database/index.html#storage-engines. Should we remove all content related to ForestDB in the 1.4 docs? It may still be useful to apps that are currently using it in production.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2855](https://issues.couchbase.com/browse/DOC-2855) and will get it fixed as soon as possible.
