### ISSUE TITLE
Mention platform 'Android' for java client on couchbase-lite 2.0 doc

### ISSUE THREAD

**Issue by sridevi-15** [couchbaselabs/couchbase-mobile-portal#759]
The documentation in the link : https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/native-api/database/index.html?language=java

Though it says platform :java, it is not for java platform, it is for Android platform.
To avoid confusion to customers, can you mention at the beginning of the page that it is for Android platform using java library. I know that it is going to be used for java platform later. Until it supports, it might be good idea to mention that it is for Android only and it supports java platform later.

**Comment by jamiltz** [comment]
Possibly use an icon to make the warning stand out ⚠️.
