### ISSUE TITLE
Channel access animation

### ISSUE THREAD

**Issue by jessliu** [couchbaselabs/couchbase-mobile-portal#77]
The Sync Gateway section needs an animated gif based on Wayne's
"Sports, San Francisco, Admin" slides (ok like 5 frames of that, and
then a few frames of some sweet looking syntax highlighted JavaScript
detailing a sync function). In the text instead of bullets it should
say "See how ______ got to 100x less code with Sync Gateway."

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2969](https://issues.couchbase.com/browse/DOC-2969) and will get it fixed as soon as possible.
