### ISSUE TITLE
CB2.0 - DP12 - "New Database" results in a ?Loop?

### ISSUE THREAD

**Issue by mwecker** [couchbaselabs/couchbase-mobile-portal#770]
I just check Couchbase 2 on .Net and UWP.

The Problem is that this:
var database = new Database("my-database");

brings me a infinity loop. 
The Breakpoint on this line comes on but the next line is never executed.
In my code is also Couchbase.Lite.Support.UWP.Activate();

And i get no Errors, any Ideas?
I use couchbase.Lite.Support.UWP Version 2.0.0-dp012

**Comment by jamiltz** [comment]
Questions/issues can be raised on the Couchbase forum https://forums.couchbase.com/c/mobile
If it turns out to be documentation related, we'll re-open a ticket here. Thanks :)

**Comment by mwecker** [comment]
I will ask in the Forum, but just as a addon. WPF Works, just UWP gets a loop
