### ISSUE TITLE
README errors (typo, and wrong paths for specs)

### ISSUE THREAD

**Issue by snej** [couchbaselabs/couchbase-mobile-portal#784]
The first sentence of the readme file doesn't make sense: _"The specs are using with Swagger UI on the following pages_"

~~More seriously, the instructions all assume there's a top level `swagger` directory in the repo, which there isn't.~~ Never mind — I didn't notice that the link I'd followed took me to the `swagger` directory, which has its own readme. I thought I was looking at the top level of the repo.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2853](https://issues.couchbase.com/browse/DOC-2853) and will get it fixed as soon as possible.
