### ISSUE TITLE
Can't find CBL Swagger JSON file from web search

### ISSUE THREAD

**Issue by snej** [couchbaselabs/couchbase-mobile-portal#785]
I was trying to find a Swagger JSON spec file for CBL, so I used Google to search for `swagger site:couchbase.com`. I found several links about using Swagger for Sync Gateway, one of was an article that contained a link to the SG spec, but I didn't find anything about CBL.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2852](https://issues.couchbase.com/browse/DOC-2852) and will get it fixed as soon as possible.
