### ISSUE TITLE
Couchbase IOS HTTPS Sync Gateway

### ISSUE THREAD

**Issue by arethasamuel** [couchbaselabs/couchbase-mobile-portal#790]
Hi how do i do SSL Sync Gateway?  DO i just specify an https://my-syncgateway:4984 url?

Would this be secure?

**Comment by rajagp** [comment]
On the SG side, you will need to enable SSL support - You can find instructions here https://developer.couchbase.com/documentation/mobile/1.4/guides/sync-gateway/configuring-ssl/index.html
Once SG has SSL enabled, you can point to it using https URI on the iOS App

**Comment by tleyden** [comment]
@arethasamuel You can also put a reverse proxy in front of Sync Gateway that handles the SSL termination.  See https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/nginx/index.html
