### ISSUE TITLE
session authenticator code example

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/couchbase-mobile-portal#799]
see https://github.com/couchbase/couchbase-lite-android/issues/1346#issuecomment-322917148

**Comment by hideki** [comment]
@jamiltz 
Is the issue reproducible with the sample code?

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2850](https://issues.couchbase.com/browse/DOC-2850) and will get it fixed as soon as possible.
