### ISSUE TITLE
Links to our Cloud Deployment Images for Couchbase Mobile

### ISSUE THREAD

**Issue by rajagp** [couchbaselabs/couchbase-mobile-portal#800]
It is very difficult to navigate to or find the cloud deployment options available for combined SG and Couchbase Server images for mobile developers. This has come up in several conversations w/ developers looking for cloud images to get started with.

Specifically
- Cloud Deployment options for AWS, GCP and Azure for 
a) SG(1.5) + CB Server (5.0)
a) SG (pre 1.5) + CB Server (pre 5.0)

There is some work going on here  https://github.com/couchbase-partners but not linked anywhere from our docs 
Ben Lackey (@benofben) has been working on this but I don't know the status. (CC @ssmotra )

**Comment by benofben** [comment]
We're working on getting it incorporated into the docs. Amarantha is taking a look at that now.  There's an email thread going on covering that subject.  I'll share some more stuff on email.

**Comment by rajagp** [comment]
Can't wait! Additionally, developers are wary of moving from CBM 1.4 to 2.0 because it breaks Cloudant support. So providing an easy to deploy cloud alternative will likely alleviate some of their fears of hosting one on their own.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2848](https://issues.couchbase.com/browse/DOC-2848) and will get it fixed as soon as possible.
