### ISSUE TITLE
Document the process for upgrading to SG 1.5.0

### ISSUE THREAD

**Issue by raghusarangapani** [couchbaselabs/couchbase-mobile-portal#801]
The recommended process for upgrading from docmeta to xattrs seems to be:

1. Upgrade SGs first docmeta -> docmeta - CBS 5.0.0 does not support TAP.
2. Upgrade the CBS cluster.
3. Enable import/xattrs on SGs.

@adamcfraser Please review/add comments.

**Comment by jamiltz** [comment]
> Upgrade SGs first docmeta -> docmeta - CBS 5.0.0 does not support TAP.

@raghusarangapani Oh that's not in the docs so far. So, regarding the TAP/DCP switch, is it possible to run SG 1.4 with CBS 5.0.0 or not at all?

**Comment by adamcfraser** [comment]
@jamiltz I think the official stance is that Sync Gateway 1.5 requires Server 5.0.  I don't know whether that's strictly required - I think that we might be able to run CBS 5.0 with SG 1.4 w/ feed_type=DCP, but I don't believe that's been completely validated by QE.

**Comment by jamiltz** [comment]
@raghusarangapani updated the current upgrade scenario to match the order of operations tested by QE. Feel free to reopen if there's anything missing/incorrect (cc @adamcfraser)

https://github.com/couchbaselabs/couchbase-mobile-portal/commit/362bb736d051b7eee3d4946951435a93dc92513a?diff=split&short_path=e259202#diff-e2592027b2d8146ca5f0b5ecc20542e0

**Comment by raghusarangapani** [comment]
After upgrading the server, the SGs needs a restart, else gocb thinks that its talking to 4.6 and 5.0

**Comment by adamcfraser** [comment]
@raghusarangapani Can you provide more specifics around that restart requirement?  gocb shouldn't care whether it's talking to 4.6 or 5.0 unless it's attempting to do xattr operations, which would imply the restart isn't needed in all cases.

**Comment by raghusarangapani** [comment]
Discussed with @adamcfraser , will run the test without restart to confirm if the upgrade test passes.
