### ISSUE TITLE
XDCR Configurations with Couchbase Mobile

### ISSUE THREAD

**Issue by ssmotra** [couchbaselabs/couchbase-mobile-portal#812]
As a user I would like to know what XDCR cluster configurations are supported with Couchbase Mobile. 

E.g Is XDCR supported for an Active-Active deployment of Couchbase Mobile?

**Comment by jamiltz** [comment]
@ssmotra we have some notes on sg-replicate vs xdcr at https://developer.couchbase.com/documentation/mobile/1.4/guides/sync-gateway/running-replications/index.html#sg-replicate-versus-xdcr Will add a sentence to mention there that XDCR in active-active mode with Couchbase Mobile isn't available. Let me know if there was anything else you were thinking should be in the docs.

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2844](https://issues.couchbase.com/browse/DOC-2844) and will get it fixed as soon as possible.
