### ISSUE TITLE
2.0 CBL Documentation: Update description around Replicator code

### ISSUE THREAD

**Issue by rajagp** [couchbaselabs/couchbase-mobile-portal#816]
In https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/native-api/replication/index.html?language=swift
Make a note here that the  the scope of the `Replicator` object must be at a class level .

Reference Issue: https://github.com/couchbase/couchbase-lite-ios/issues/1926#issuecomment-335490373

**Comment by jamiltz** [comment]
Thanks for your feedback! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2842](https://issues.couchbase.com/browse/DOC-2842) and will get it fixed as soon as possible.
