### ISSUE TITLE
Add additional notes for _user endpoint valid names

### ISSUE THREAD

**Issue by ajres** [couchbaselabs/couchbase-mobile-portal#817]

**Comment by jamiltz** [comment]
We can document that in the user parameter in swagger which is being reused on all those endpoints
- https://github.com/couchbaselabs/couchbase-mobile-portal/blob/master/swagger/1.5/sync-gateway-admin....
- https://github.com/couchbaselabs/couchbase-mobile-portal/blob/master/swagger/1.5/sync-gateway-admin....
If you open a PR with a change to those lines I can make sure it is displayed correctly on the website afterwards.
