### ISSUE TITLE
Add documentation for sync function expiry

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/couchbase-mobile-portal#823]
Related PR:
https://github.com/couchbase/sync_gateway/pull/3016

**Comment by tleyden** [comment]
@jamiltz also I can't find any docs for the "non-sync function" expiry.  

The best docs I could find were here:

https://github.com/couchbase/sync_gateway/commit/382149ef755675bded4cc6f14517ea9871a164ae

**Comment by tleyden** [comment]
@adamcfraser found the content here: https://github.com/couchbaselabs/couchbase-mobile-portal/blob/1960b8767370fcf9fb089749e8810fec9a996f71/swagger/1.5/sync-gateway-admin.yaml#L728

It's only on the admin rest api though.  We need to add to the public rest api yaml

**Comment by adamcfraser** [comment]
The existing documentation (linked above by Traun) also doesn't specify the format of the _exp property - it would be nice to also get that into the docs.

**Comment by jamiltz** [comment]
Thanks for your feedback! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2840](https://issues.couchbase.com/browse/DOC-2840) and will get it fixed as soon as possible.

**Comment by jamiltz** [comment]
Thanks for your feedback! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2841](https://issues.couchbase.com/browse/DOC-2841) and will get it fixed as soon as possible.
