### ISSUE TITLE
Review Sync Gateway OIDC config + documentation

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-mobile-portal#825]
I merged https://github.com/couchbaselabs/couchbase-mobile-portal/pull/822/files, and then after discussing with @adamcfraser, it turns out this needs more testing and validation.

We should take this opportunity to make sure that the docs and samples are in sync.

Note from @adamcfraser: 

> callback_url shouldn't be hardcoding localhost in a real-world deployment

QE ticket to increase test coverage: https://github.com/couchbaselabs/mobile-testkit/issues/1441

**Comment by jamiltz** [comment]
Thanks for your feedback! We've moved the ticket to [https://github.com/couchbaselabs/couchbase-mobile-portal/issues/825](https://github.com/couchbaselabs/couchbase-mobile-portal/issues/825) and will get it fixed as soon as possible.
