### ISSUE TITLE
SG REST API doesn't specify rev parameter as required for doc PUT update

### ISSUE THREAD

**Issue by greenais** [couchbaselabs/couchbase-mobile-portal#828]
It was corrected for DELETE (in API docs rev is marked as required now) but in PUT update request rev is stated as optional (which is obviosly incorrect).
That leads to situation where doc is initially created but then not being updated with 409 statusCode in SG response.

**Comment by jamiltz** [comment]
Thanks for your feedback! We've moved the ticket to https://issues.couchbase.com/projects/DOC/issues/DOC-2831 and will get it fixed as soon as possible.
