### ISSUE TITLE
Error in CouchBase mobile 2.0 / Document docs?

### ISSUE THREAD

**Issue by SilvanaP** [couchbaselabs/couchbase-mobile-portal#839]
Could it be that there is an error in the docs of the Document class? 
When I try to instantize a new Document as described with "Document d = new Document()", I get the compile error: "Cannot resolve constructor Document()".

(The doc is found on: https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/native-api/document/index.html )

Shouldn't it be MutableDocument document = new MutableDocument(); ?
I found this in the mobile-travel-tutorial for 2.0, and at least the compiler is not complaining anymore :)

**Comment by jamiltz** [comment]
with the API changes, the documentation was a bit behind, should be up to date with the [Beta release](https://forums.couchbase.com/t/announcing-couchbase-mobile-2-0-beta/15760) now https://developer.couchbase.com/documentation/mobile/2.0/couchbase-lite/index.html
