### ISSUE TITLE
Add additional information about time out configs

### ISSUE THREAD

**Issue by jamescooke** [couchbaselabs/couchbase-mobile-portal#841]
Additional information about some configuration options would be really helpful:

* `serverReadTimeout`: https://github.com/couchbaselabs/couchbase-mobile-portal/blob/master/configs/1.5/sg.yaml#L547
  - What is the default value?
  - What `https` connections does this effect? Is it client / CB Lite side? Is it CB cluster side? Is it both? Does it effect admin port connections?
  - What are the implications of turning up / down this value?

* `serverWriteTimeout`: https://github.com/couchbaselabs/couchbase-mobile-portal/blob/master/configs/1.5/sg.yaml#L550 (similar to above)
  - What is the default value?
  - Which connections does this effect?
  - What are the implications of tuning this value?

**Comment by tleyden** [comment]
I checked the Sync Gateway code, and these are just propagated to the Go http.Server:

https://golang.org/pkg/net/http/#Server

See:

```
        // ReadTimeout is the maximum duration for reading the entire
        // request, including the body.
        //
        // Because ReadTimeout does not let Handlers make per-request
        // decisions on each request body's acceptable deadline or
        // upload rate, most users will prefer to use
        // ReadHeaderTimeout. It is valid to use them both.
        ReadTimeout time.Duration

        // WriteTimeout is the maximum duration before timing out
        // writes of the response. It is reset whenever a new
        // request's header is read. Like ReadTimeout, it does not
        // let Handlers make decisions on a per-request basis.
        WriteTimeout time.Duration
```

**Comment by jamescooke** [comment]
OK so that tallies with this reply: https://github.com/couchbase/sync_gateway/issues/3212#issuecomment-358471559

> The serverReadTimeout and serverWriteTimeout properties only modify SG's HTTP server timeouts.

My understanding is that these setting therefore only effect the client connections from CB Lite and on the Admin port - I hope that's right :thinking:

**Comment by tleyden** [comment]
I would expect those settings to apply on both the public port (4984) and the admin port (4985)

**Comment by jamiltz** [comment]
added this info to the reference (https://github.com/couchbaselabs/couchbase-mobile-portal/commit/b467a6e245de326e3b432a2fafd9cade85e654c9) https://developer.couchbase.com/documentation/mobile/1.5/guides/sync-gateway/config-properties/index.html#1.5/serverReadTimeout If you feel there should be something else mentioned in there just let us know. Thanks for the feedback!
