### ISSUE TITLE
Remove all references to SQLite from 2.0 documentation

### ISSUE THREAD

**Issue by ssmotra** [couchbaselabs/couchbase-mobile-portal#843]
Remove all references to SQLite from 2.0 documentation

**Comment by rajagp** [comment]
@ssmotra Is there a reason for this ?  I've had to mention this in my talks and such because developers have often been curious about our storage engine

**Comment by jamiltz** [comment]
Currently the only reference to SQLite in 2.0 docs is in the migration paragraph https://github.com/couchbaselabs/couchbase-mobile-portal/blob/master/md-docs/_20/guides/couchbase-lite/swift.md#migrating-from-1x-databases which should be fine as we need to point out migration is supported for SQLite backed databases but not ForestDB. Closing this ticket but it should be re-opened if something needs to be changed.
