### ISSUE TITLE
Remove references to BLIP from 2.0 documentation

### ISSUE THREAD

**Issue by ssmotra** [couchbaselabs/couchbase-mobile-portal#844]
Remove all references to BLIP from 2.0 documentation.

**Comment by rajagp** [comment]
@ssmotra : So what are we going to specify  instead - just "Websockets based" ? What are we are going to say when people ask what the "blip" in "blip://" in URL?

Also, Is this a requirement for all content (blogs, talks etc) as well ?

**Comment by pasin** [comment]
Current the URLEndpoint doesn't take the URL so users are not visible to the URL scheme that we use. However @snej points that ws:// and wss:// are the standard URL scheme for web socket, we may use that. I created https://github.com/couchbaselabs/couchbase-lite-apiv2/issues/194 to look into this.

**Comment by jamiltz** [comment]
references to blip and `blip://` usage removed in the commit above.
