### ISSUE TITLE
Add information on query parameters to CBL 2.0 pages

### ISSUE THREAD

**Issue by borrrden** [couchbaselabs/couchbase-mobile-portal#849]
There is a good deal of information on other aspects of query but none that I could find for using parameters in queries.

**Comment by jamiltz** [comment]
It seems to be settable in [query.parameters](http://docs.couchbase.com/mobile/2.0/couchbase-lite-net/db022/html/T_Couchbase_Lite_Query_Parameters.htm) at query time and used in the query under [Expression.parameter(...)](http://docs.couchbase.com/mobile/2.0/couchbase-lite-net/db022/html/M_Couchbase_Lite_Query_Expression_Parameter.htm)

What is the advantage of using a parameter over doing string interpolation with `Expression.string(...)` for example?

**Comment by jamiltz** [comment]
@rajagp did you try an example of a query with parameters before?

**Comment by jamiltz** [comment]
Moved to https://issues.couchbase.com/browse/DOC-4724
