### ISSUE TITLE
Make it clearer that auth related statements in Sync functions are no-ops over admin port / root user

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-mobile-portal#853]
I ran into this while helping a user on the forum, asking how to differentiate between normal users and the root user coming in on the admin port. 

The answer is that calls like `requireUser()` are no-ops when they come over the admin port.  I think we should call that out in the sync function docs.

**Comment by tleyden** [comment]
Related [forum post](https://forums.couchbase.com/t/sync-gateway-check-if-admin-call-superuser/15658)

Related [SG github issue](https://github.com/couchbase/sync_gateway/issues/3276)

**Comment by HodGreeley** [comment]
Right now I only see this mentioned in the context of a resync.  

In the same vein, it's not clear what the context is for a document written directly to Couchbase Server as it gets processed.

**Comment by jamiltz** [comment]
Yeah it wasn't mentioned on the authorizing users page so added a paragraph (see commit linked to this issue).

As @HodGreeley said, it's also mentioned in the [re-sync](https://developer.couchbase.com/documentation/mobile/1.5/guides/sync-gateway/sync-function-api-guide/index.html#when-should-you-run-a-re-sync) paragraph.

> In the same vein, it's not clear what the context is for a document written directly to Couchbase Server as it gets processed.

We talk about it [here](https://developer.couchbase.com/documentation/mobile/1.5/guides/sync-gateway/config-properties/index.html#1.5/databases-foo_db-enable_shared_bucket_access).

Closing this ticket but let me know if there's anywhere else to mention it.
