### ISSUE TITLE
Link to v1.5 views guide seems broken

### ISSUE THREAD

**Issue by jamescooke** [couchbaselabs/couchbase-mobile-portal#856]
A link seems to be broken since a recent update to documentation to include v2 stuff.

Steps to reproduce:

* Visit the "query a view" API document here https://developer.couchbase.com/documentation/mobile/1.5/references/sync-gateway/admin-rest-api/index.html#/query/get__db___design__ddoc___view__view_

* Click on " this guide " which links to https://developer.couchbase.com/documentation/mobile/1.5/guides/sync-gateway/views/index.html

* Some redirect occurs and my browser ends up on the v2 Sync Gateway home page here: https://developer.couchbase.com/documentation/mobile/2.0/guides/sync-gateway/index.html

What should have happened is that the old v1.5 views guide should have been shown.

**Comment by jamiltz** [comment]
@jamescooke thanks for the feedback. The view query endpoint on the public port is not (never was) officially supported. So it was removed from the docs.

But you've raised an interested question about whether that same endpoint on the admin port is supported (i.e does it require the `unsupported.view..` key to be set explicitly in the config).

**Comment by jamiltz** [comment]
@jamescooke turns out the endpoint on the admin port doesn't actually need any config setting so is supported. We've updated the docs to remove the sentence that was confusing. Let us know if you have any further questions.

**Comment by jamescooke** [comment]
OK - that's a nice cleanup.

My further question is where has the view guide for the admin port gone? I'm pretty sure there was one and that it was here https://developer.couchbase.com/documentation/mobile/1.5/guides/sync-gateway/views/index.html - but maybe I'm getting confused? Maybe that URL redirected to another page?

When I do `curl` on that URL I get a page that has a title `<h1>Creating and querying a View</h1>`, but it seems like it contains no content. Has this been removed? Oh yeah - here it is - I'll just read the doc from the commit's parent :joy:  https://github.com/couchbaselabs/couchbase-mobile-portal/commit/909ce7bf392028f06156233fde5d1f72e837e47e :+1:
