### ISSUE TITLE
Instructions for how to add Couchbase Lite to a Mac app

### ISSUE THREAD

**Issue by snej** [couchbaselabs/couchbase-mobile-portal#87]
We have a tutorial for [creating an iOS app](http://developer.couchbase.com/mobile/develop/training/build-first-ios-app/index.html), but not one for creating a Mac app. Some of the steps are different, especially how to embed the Couchbase Lite framework. (There's a [wiki document](https://github.com/couchbase/couchbase-lite-ios/wiki/Building-Couchbase-Lite#linking-couchbase-lite-into-your-own-app) describing the steps for Mac OS.)

**Comment by jamiltz** [comment]
Now documented at http://developer.couchbase.com/documentation/mobile/1.3/installation/ios/index.html#os-x
